// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: symphony/collateral/v1beta1/collateral.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	// List of all allowed assets (BTC, ETH, SOL, etc.)
	AllowedAssets []*AllowedAsset `protobuf:"bytes,1,rep,name=allowed_assets,json=allowedAssets,proto3" json:"allowed_assets,omitempty"`
	// Denom of the system stablecoin (e.g., mld)
	StableDenom string `protobuf:"bytes,2,opt,name=stable_denom,json=stableDenom,proto3" json:"stable_denom,omitempty"`
	// Whether withdrawals are globally enabled
	WithdrawalsEnabled bool `protobuf:"varint,3,opt,name=withdrawals_enabled,json=withdrawalsEnabled,proto3" json:"withdrawals_enabled,omitempty"`
	// Whether price-based adjustment logic is active
	PriceAdjustmentEnabled bool `protobuf:"varint,4,opt,name=price_adjustment_enabled,json=priceAdjustmentEnabled,proto3" json:"price_adjustment_enabled,omitempty"`
	// Minimum collateral ratio required to allow withdrawals
	MinCollateralRatio string `protobuf:"bytes,5,opt,name=min_collateral_ratio,json=minCollateralRatio,proto3" json:"min_collateral_ratio,omitempty"`
	// Maximum different asset types allowed per user
	MaxUserAssets string `protobuf:"bytes,6,opt,name=max_user_assets,json=maxUserAssets,proto3" json:"max_user_assets,omitempty"`
	// Prefix for all tracking-token denoms (like "t")
	TrackTokenPrefix string `protobuf:"bytes,7,opt,name=track_token_prefix,json=trackTokenPrefix,proto3" json:"track_token_prefix,omitempty"`
	// Types that are valid to be assigned to XOracleAddr:
	//	*Params_OracleAddr
	XOracleAddr isParams_XOracleAddr `protobuf_oneof:"_oracle_addr"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_c126c7b26075d84f, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

type isParams_XOracleAddr interface {
	isParams_XOracleAddr()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Params_OracleAddr struct {
	OracleAddr string `protobuf:"bytes,8,opt,name=oracle_addr,json=oracleAddr,proto3,oneof" json:"oracle_addr,omitempty"`
}

func (*Params_OracleAddr) isParams_XOracleAddr() {}

func (m *Params) GetXOracleAddr() isParams_XOracleAddr {
	if m != nil {
		return m.XOracleAddr
	}
	return nil
}

func (m *Params) GetAllowedAssets() []*AllowedAsset {
	if m != nil {
		return m.AllowedAssets
	}
	return nil
}

func (m *Params) GetStableDenom() string {
	if m != nil {
		return m.StableDenom
	}
	return ""
}

func (m *Params) GetWithdrawalsEnabled() bool {
	if m != nil {
		return m.WithdrawalsEnabled
	}
	return false
}

func (m *Params) GetPriceAdjustmentEnabled() bool {
	if m != nil {
		return m.PriceAdjustmentEnabled
	}
	return false
}

func (m *Params) GetMinCollateralRatio() string {
	if m != nil {
		return m.MinCollateralRatio
	}
	return ""
}

func (m *Params) GetMaxUserAssets() string {
	if m != nil {
		return m.MaxUserAssets
	}
	return ""
}

func (m *Params) GetTrackTokenPrefix() string {
	if m != nil {
		return m.TrackTokenPrefix
	}
	return ""
}

func (m *Params) GetOracleAddr() string {
	if x, ok := m.GetXOracleAddr().(*Params_OracleAddr); ok {
		return x.OracleAddr
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Params) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Params_OracleAddr)(nil),
	}
}

type AllowedAsset struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	// Types that are valid to be assigned to XOracleId:
	//
	//	*AllowedAsset_OracleId
	XOracleId isAllowedAsset_XOracleId `protobuf_oneof:"_oracle_id"`
	// Types that are valid to be assigned to XLtv:
	//
	//	*AllowedAsset_Ltv
	XLtv isAllowedAsset_XLtv `protobuf_oneof:"_ltv"`
	// Types that are valid to be assigned to XWithdrawFeeBp:
	//
	//	*AllowedAsset_WithdrawFeeBp
	XWithdrawFeeBp isAllowedAsset_XWithdrawFeeBp `protobuf_oneof:"_withdraw_fee_bp"`
}

func (m *AllowedAsset) Reset()         { *m = AllowedAsset{} }
func (m *AllowedAsset) String() string { return proto.CompactTextString(m) }
func (*AllowedAsset) ProtoMessage()    {}
func (*AllowedAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_c126c7b26075d84f, []int{1}
}
func (m *AllowedAsset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AllowedAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AllowedAsset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AllowedAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowedAsset.Merge(m, src)
}
func (m *AllowedAsset) XXX_Size() int {
	return m.Size()
}
func (m *AllowedAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowedAsset.DiscardUnknown(m)
}

var xxx_messageInfo_AllowedAsset proto.InternalMessageInfo

type isAllowedAsset_XOracleId interface {
	isAllowedAsset_XOracleId()
	MarshalTo([]byte) (int, error)
	Size() int
}
type isAllowedAsset_XLtv interface {
	isAllowedAsset_XLtv()
	MarshalTo([]byte) (int, error)
	Size() int
}
type isAllowedAsset_XWithdrawFeeBp interface {
	isAllowedAsset_XWithdrawFeeBp()
	MarshalTo([]byte) (int, error)
	Size() int
}

type AllowedAsset_OracleId struct {
	OracleId string `protobuf:"bytes,3,opt,name=oracle_id,json=oracleId,proto3,oneof" json:"oracle_id,omitempty"`
}
type AllowedAsset_Ltv struct {
	Ltv uint64 `protobuf:"varint,4,opt,name=ltv,proto3,oneof" json:"ltv,omitempty"`
}
type AllowedAsset_WithdrawFeeBp struct {
	WithdrawFeeBp uint64 `protobuf:"varint,5,opt,name=withdraw_fee_bp,json=withdrawFeeBp,proto3,oneof" json:"withdraw_fee_bp,omitempty"`
}

func (*AllowedAsset_OracleId) isAllowedAsset_XOracleId()           {}
func (*AllowedAsset_Ltv) isAllowedAsset_XLtv()                     {}
func (*AllowedAsset_WithdrawFeeBp) isAllowedAsset_XWithdrawFeeBp() {}

func (m *AllowedAsset) GetXOracleId() isAllowedAsset_XOracleId {
	if m != nil {
		return m.XOracleId
	}
	return nil
}
func (m *AllowedAsset) GetXLtv() isAllowedAsset_XLtv {
	if m != nil {
		return m.XLtv
	}
	return nil
}
func (m *AllowedAsset) GetXWithdrawFeeBp() isAllowedAsset_XWithdrawFeeBp {
	if m != nil {
		return m.XWithdrawFeeBp
	}
	return nil
}

func (m *AllowedAsset) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *AllowedAsset) GetOracleId() string {
	if x, ok := m.GetXOracleId().(*AllowedAsset_OracleId); ok {
		return x.OracleId
	}
	return ""
}

func (m *AllowedAsset) GetLtv() uint64 {
	if x, ok := m.GetXLtv().(*AllowedAsset_Ltv); ok {
		return x.Ltv
	}
	return 0
}

func (m *AllowedAsset) GetWithdrawFeeBp() uint64 {
	if x, ok := m.GetXWithdrawFeeBp().(*AllowedAsset_WithdrawFeeBp); ok {
		return x.WithdrawFeeBp
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AllowedAsset) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AllowedAsset_OracleId)(nil),
		(*AllowedAsset_Ltv)(nil),
		(*AllowedAsset_WithdrawFeeBp)(nil),
	}
}

func init() {
	proto.RegisterType((*Params)(nil), "symphony.collateral.v1beta1.Params")
	proto.RegisterType((*AllowedAsset)(nil), "symphony.collateral.v1beta1.AllowedAsset")
}

func init() {
	proto.RegisterFile("symphony/collateral/v1beta1/collateral.proto", fileDescriptor_c126c7b26075d84f)
}

var fileDescriptor_c126c7b26075d84f = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x4d, 0x6e, 0x13, 0x31,
	0x1c, 0xc5, 0xe3, 0x26, 0x0d, 0xa9, 0x93, 0xb4, 0x95, 0x09, 0x68, 0x28, 0xd2, 0x28, 0x54, 0x08,
	0x05, 0x51, 0x32, 0xb4, 0x48, 0xc0, 0x36, 0xe1, 0x43, 0x61, 0x17, 0x8d, 0x60, 0xc3, 0xc6, 0xf2,
	0xcc, 0x38, 0xc9, 0x50, 0x7b, 0x3c, 0xb2, 0x9d, 0xaf, 0x1b, 0x74, 0xc9, 0x29, 0x38, 0x01, 0x87,
	0x60, 0xd9, 0x25, 0x4b, 0x94, 0x5c, 0x04, 0xd9, 0xce, 0x84, 0x11, 0x0b, 0x76, 0xf9, 0xbf, 0xdf,
	0x7b, 0x9e, 0xbf, 0x9f, 0x1c, 0x78, 0xa1, 0xd6, 0x3c, 0x9f, 0x89, 0x6c, 0x1d, 0xc4, 0x82, 0x31,
	0xa2, 0xa9, 0x24, 0x2c, 0x58, 0x5c, 0x46, 0x54, 0x93, 0xcb, 0x92, 0xd4, 0xcf, 0xa5, 0xd0, 0x02,
	0x3d, 0x2c, 0xdc, 0xfd, 0x12, 0xda, 0xb9, 0xcf, 0x1e, 0xc4, 0x42, 0x71, 0xa1, 0xb0, 0xb5, 0x06,
	0x6e, 0x70, 0xb9, 0xb3, 0xce, 0x54, 0x4c, 0x85, 0xd3, 0xcd, 0xaf, 0x9d, 0xea, 0x4f, 0x85, 0x98,
	0x32, 0x1a, 0xd8, 0x29, 0x9a, 0x4f, 0x82, 0x64, 0x2e, 0x89, 0x4e, 0x45, 0x56, 0x70, 0x77, 0x46,
	0x10, 0x11, 0x45, 0x4b, 0x3b, 0xa5, 0x3b, 0x7e, 0xfe, 0xbd, 0x0a, 0xeb, 0x63, 0x22, 0x09, 0x57,
	0x68, 0x0c, 0x8f, 0x09, 0x63, 0x62, 0x49, 0x13, 0x4c, 0x94, 0xa2, 0x5a, 0x79, 0xa0, 0x5b, 0xed,
	0x35, 0xaf, 0x9e, 0xf6, 0xff, 0xb3, 0x71, 0x7f, 0xe0, 0x22, 0x03, 0x93, 0x08, 0xdb, 0xa4, 0x34,
	0x29, 0xf4, 0x08, 0xb6, 0x94, 0x26, 0x11, 0xa3, 0x38, 0xa1, 0x99, 0xe0, 0xde, 0x41, 0x17, 0xf4,
	0x8e, 0xc2, 0xa6, 0xd3, 0xde, 0x19, 0x09, 0x05, 0xf0, 0xee, 0x32, 0xd5, 0xb3, 0x44, 0x92, 0x25,
	0x61, 0x0a, 0xd3, 0xcc, 0xa0, 0xc4, 0xab, 0x76, 0x41, 0xaf, 0x11, 0xa2, 0x12, 0x7a, 0xef, 0x08,
	0x7a, 0x03, 0xbd, 0x5c, 0xa6, 0x31, 0xc5, 0x24, 0xf9, 0x3a, 0x57, 0x9a, 0xd3, 0x4c, 0xef, 0x53,
	0x35, 0x9b, 0xba, 0x6f, 0xf9, 0x60, 0x8f, 0x8b, 0xe4, 0x0b, 0xd8, 0xe1, 0x69, 0x86, 0xff, 0xde,
	0x01, 0xdb, 0xa6, 0xbc, 0x43, 0xbb, 0x15, 0xe2, 0x69, 0xf6, 0x76, 0x8f, 0x42, 0x43, 0xd0, 0x13,
	0x78, 0xc2, 0xc9, 0x0a, 0xcf, 0x15, 0x95, 0x45, 0x25, 0x75, 0x6b, 0x6e, 0x73, 0xb2, 0xfa, 0xac,
	0xa8, 0xdc, 0xdd, 0xf3, 0x02, 0x22, 0x2d, 0x49, 0x7c, 0x8d, 0xb5, 0xb8, 0xa6, 0x19, 0xce, 0x25,
	0x9d, 0xa4, 0x2b, 0xef, 0x8e, 0xb5, 0x9e, 0x5a, 0xf2, 0xc9, 0x80, 0xb1, 0xd5, 0xd1, 0x63, 0xd8,
	0x14, 0x92, 0xc4, 0xcc, 0x5c, 0x21, 0x91, 0x5e, 0xc3, 0xd8, 0x46, 0x95, 0x10, 0x3a, 0x71, 0x90,
	0x24, 0xf2, 0x06, 0x80, 0xe1, 0x31, 0x6c, 0xe1, 0x92, 0xed, 0xfc, 0x07, 0x80, 0xad, 0x72, 0xd7,
	0xa8, 0x03, 0x0f, 0x5d, 0xab, 0xc0, 0x7e, 0xc7, 0x0d, 0xa8, 0x0b, 0x8f, 0x76, 0xa9, 0xd4, 0xb5,
	0x68, 0x8e, 0x6e, 0x38, 0xe9, 0x63, 0x72, 0x03, 0x00, 0xba, 0x07, 0xab, 0x4c, 0x2f, 0x6c, 0x57,
	0xb5, 0x11, 0x08, 0xcd, 0x60, 0xe4, 0x67, 0xf0, 0xa4, 0x68, 0x1b, 0x4f, 0x28, 0xc5, 0x51, 0x6e,
	0x8b, 0xa9, 0x8d, 0x0e, 0xc2, 0x76, 0x01, 0x3e, 0x50, 0x3a, 0xcc, 0xcd, 0x72, 0x2d, 0x08, 0xf1,
	0xfe, 0x33, 0xc3, 0x3a, 0xac, 0x61, 0xa6, 0x17, 0x43, 0x04, 0x4f, 0xf1, 0x3f, 0x67, 0x0c, 0xc7,
	0x3f, 0x37, 0x3e, 0xb8, 0xdd, 0xf8, 0xe0, 0xf7, 0xc6, 0x07, 0xdf, 0xb6, 0x7e, 0xe5, 0x76, 0xeb,
	0x57, 0x7e, 0x6d, 0xfd, 0xca, 0x97, 0x57, 0xd3, 0x54, 0xcf, 0xe6, 0x51, 0x3f, 0x16, 0x3c, 0xb0,
	0x6f, 0x34, 0x55, 0xcf, 0x19, 0x89, 0x54, 0x31, 0x04, 0x8b, 0xab, 0xd7, 0xc1, 0xaa, 0xfc, 0x97,
	0xd2, 0xeb, 0x9c, 0xaa, 0xa8, 0x6e, 0x1f, 0xee, 0xcb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7f,
	0x24, 0xee, 0x7b, 0x76, 0x03, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XOracleAddr != nil {
		{
			size := m.XOracleAddr.Size()
			i -= size
			if _, err := m.XOracleAddr.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.TrackTokenPrefix) > 0 {
		i -= len(m.TrackTokenPrefix)
		copy(dAtA[i:], m.TrackTokenPrefix)
		i = encodeVarintCollateral(dAtA, i, uint64(len(m.TrackTokenPrefix)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.MaxUserAssets) > 0 {
		i -= len(m.MaxUserAssets)
		copy(dAtA[i:], m.MaxUserAssets)
		i = encodeVarintCollateral(dAtA, i, uint64(len(m.MaxUserAssets)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.MinCollateralRatio) > 0 {
		i -= len(m.MinCollateralRatio)
		copy(dAtA[i:], m.MinCollateralRatio)
		i = encodeVarintCollateral(dAtA, i, uint64(len(m.MinCollateralRatio)))
		i--
		dAtA[i] = 0x2a
	}
	if m.PriceAdjustmentEnabled {
		i--
		if m.PriceAdjustmentEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.WithdrawalsEnabled {
		i--
		if m.WithdrawalsEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.StableDenom) > 0 {
		i -= len(m.StableDenom)
		copy(dAtA[i:], m.StableDenom)
		i = encodeVarintCollateral(dAtA, i, uint64(len(m.StableDenom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AllowedAssets) > 0 {
		for iNdEx := len(m.AllowedAssets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AllowedAssets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCollateral(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Params_OracleAddr) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params_OracleAddr) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= len(m.OracleAddr)
	copy(dAtA[i:], m.OracleAddr)
	i = encodeVarintCollateral(dAtA, i, uint64(len(m.OracleAddr)))
	i--
	dAtA[i] = 0x42
	return len(dAtA) - i, nil
}
func (m *AllowedAsset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AllowedAsset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AllowedAsset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XWithdrawFeeBp != nil {
		{
			size := m.XWithdrawFeeBp.Size()
			i -= size
			if _, err := m.XWithdrawFeeBp.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.XLtv != nil {
		{
			size := m.XLtv.Size()
			i -= size
			if _, err := m.XLtv.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.XOracleId != nil {
		{
			size := m.XOracleId.Size()
			i -= size
			if _, err := m.XOracleId.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintCollateral(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AllowedAsset_OracleId) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AllowedAsset_OracleId) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= len(m.OracleId)
	copy(dAtA[i:], m.OracleId)
	i = encodeVarintCollateral(dAtA, i, uint64(len(m.OracleId)))
	i--
	dAtA[i] = 0x1a
	return len(dAtA) - i, nil
}
func (m *AllowedAsset_Ltv) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AllowedAsset_Ltv) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintCollateral(dAtA, i, uint64(m.Ltv))
	i--
	dAtA[i] = 0x20
	return len(dAtA) - i, nil
}
func (m *AllowedAsset_WithdrawFeeBp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AllowedAsset_WithdrawFeeBp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintCollateral(dAtA, i, uint64(m.WithdrawFeeBp))
	i--
	dAtA[i] = 0x28
	return len(dAtA) - i, nil
}
func encodeVarintCollateral(dAtA []byte, offset int, v uint64) int {
	offset -= sovCollateral(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AllowedAssets) > 0 {
		for _, e := range m.AllowedAssets {
			l = e.Size()
			n += 1 + l + sovCollateral(uint64(l))
		}
	}
	l = len(m.StableDenom)
	if l > 0 {
		n += 1 + l + sovCollateral(uint64(l))
	}
	if m.WithdrawalsEnabled {
		n += 2
	}
	if m.PriceAdjustmentEnabled {
		n += 2
	}
	l = len(m.MinCollateralRatio)
	if l > 0 {
		n += 1 + l + sovCollateral(uint64(l))
	}
	l = len(m.MaxUserAssets)
	if l > 0 {
		n += 1 + l + sovCollateral(uint64(l))
	}
	l = len(m.TrackTokenPrefix)
	if l > 0 {
		n += 1 + l + sovCollateral(uint64(l))
	}
	if m.XOracleAddr != nil {
		n += m.XOracleAddr.Size()
	}
	return n
}

func (m *Params_OracleAddr) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OracleAddr)
	n += 1 + l + sovCollateral(uint64(l))
	return n
}
func (m *AllowedAsset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovCollateral(uint64(l))
	}
	if m.XOracleId != nil {
		n += m.XOracleId.Size()
	}
	if m.XLtv != nil {
		n += m.XLtv.Size()
	}
	if m.XWithdrawFeeBp != nil {
		n += m.XWithdrawFeeBp.Size()
	}
	return n
}

func (m *AllowedAsset_OracleId) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OracleId)
	n += 1 + l + sovCollateral(uint64(l))
	return n
}
func (m *AllowedAsset_Ltv) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovCollateral(uint64(m.Ltv))
	return n
}
func (m *AllowedAsset_WithdrawFeeBp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovCollateral(uint64(m.WithdrawFeeBp))
	return n
}

func sovCollateral(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCollateral(x uint64) (n int) {
	return sovCollateral(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCollateral
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedAssets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCollateral
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCollateral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedAssets = append(m.AllowedAssets, &AllowedAsset{})
			if err := m.AllowedAssets[len(m.AllowedAssets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StableDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StableDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalsEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WithdrawalsEnabled = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceAdjustmentEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PriceAdjustmentEnabled = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCollateralRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinCollateralRatio = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxUserAssets", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxUserAssets = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrackTokenPrefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrackTokenPrefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.XOracleAddr = &Params_OracleAddr{string(dAtA[iNdEx:postIndex])}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCollateral(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCollateral
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AllowedAsset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCollateral
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AllowedAsset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AllowedAsset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.XOracleId = &AllowedAsset_OracleId{string(dAtA[iNdEx:postIndex])}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ltv", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.XLtv = &AllowedAsset_Ltv{v}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawFeeBp", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.XWithdrawFeeBp = &AllowedAsset_WithdrawFeeBp{v}
		default:
			iNdEx = preIndex
			skippy, err := skipCollateral(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCollateral
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCollateral(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCollateral
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCollateral
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCollateral
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCollateral
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCollateral        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCollateral          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCollateral = fmt.Errorf("proto: unexpected end of group")
)
