// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: symphony/collateral/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryCollateralParamsRequest struct {
}

func (m *QueryCollateralParamsRequest) Reset()         { *m = QueryCollateralParamsRequest{} }
func (m *QueryCollateralParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCollateralParamsRequest) ProtoMessage()    {}
func (*QueryCollateralParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_331dea947f6bd23d, []int{0}
}
func (m *QueryCollateralParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCollateralParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCollateralParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCollateralParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCollateralParamsRequest.Merge(m, src)
}
func (m *QueryCollateralParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCollateralParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCollateralParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCollateralParamsRequest proto.InternalMessageInfo

type QueryCollateralParamsResponse struct {
	Params *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *QueryCollateralParamsResponse) Reset()         { *m = QueryCollateralParamsResponse{} }
func (m *QueryCollateralParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCollateralParamsResponse) ProtoMessage()    {}
func (*QueryCollateralParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_331dea947f6bd23d, []int{1}
}
func (m *QueryCollateralParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCollateralParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCollateralParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCollateralParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCollateralParamsResponse.Merge(m, src)
}
func (m *QueryCollateralParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCollateralParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCollateralParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCollateralParamsResponse proto.InternalMessageInfo

func (m *QueryCollateralParamsResponse) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

type QueryUserCollateralRequest struct {
	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (m *QueryUserCollateralRequest) Reset()         { *m = QueryUserCollateralRequest{} }
func (m *QueryUserCollateralRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserCollateralRequest) ProtoMessage()    {}
func (*QueryUserCollateralRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_331dea947f6bd23d, []int{2}
}
func (m *QueryUserCollateralRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserCollateralRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserCollateralRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserCollateralRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserCollateralRequest.Merge(m, src)
}
func (m *QueryUserCollateralRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserCollateralRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserCollateralRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserCollateralRequest proto.InternalMessageInfo

func (m *QueryUserCollateralRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type UserAssetPosition struct {
	Asset    *types.Coin `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	UsdValue string      `protobuf:"bytes,2,opt,name=usd_value,json=usdValue,proto3" json:"usd_value,omitempty"`
}

func (m *UserAssetPosition) Reset()         { *m = UserAssetPosition{} }
func (m *UserAssetPosition) String() string { return proto.CompactTextString(m) }
func (*UserAssetPosition) ProtoMessage()    {}
func (*UserAssetPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_331dea947f6bd23d, []int{3}
}
func (m *UserAssetPosition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserAssetPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserAssetPosition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserAssetPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAssetPosition.Merge(m, src)
}
func (m *UserAssetPosition) XXX_Size() int {
	return m.Size()
}
func (m *UserAssetPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAssetPosition.DiscardUnknown(m)
}

var xxx_messageInfo_UserAssetPosition proto.InternalMessageInfo

func (m *UserAssetPosition) GetAsset() *types.Coin {
	if m != nil {
		return m.Asset
	}
	return nil
}

func (m *UserAssetPosition) GetUsdValue() string {
	if m != nil {
		return m.UsdValue
	}
	return ""
}

type QueryUserCollateralResponse struct {
	Positions       []*UserAssetPosition `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	TotalUsdValue   string               `protobuf:"bytes,2,opt,name=total_usd_value,json=totalUsdValue,proto3" json:"total_usd_value,omitempty"`
	WithdrawableUsd string               `protobuf:"bytes,3,opt,name=withdrawable_usd,json=withdrawableUsd,proto3" json:"withdrawable_usd,omitempty"`
}

func (m *QueryUserCollateralResponse) Reset()         { *m = QueryUserCollateralResponse{} }
func (m *QueryUserCollateralResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUserCollateralResponse) ProtoMessage()    {}
func (*QueryUserCollateralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_331dea947f6bd23d, []int{4}
}
func (m *QueryUserCollateralResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserCollateralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserCollateralResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserCollateralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserCollateralResponse.Merge(m, src)
}
func (m *QueryUserCollateralResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserCollateralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserCollateralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserCollateralResponse proto.InternalMessageInfo

func (m *QueryUserCollateralResponse) GetPositions() []*UserAssetPosition {
	if m != nil {
		return m.Positions
	}
	return nil
}

func (m *QueryUserCollateralResponse) GetTotalUsdValue() string {
	if m != nil {
		return m.TotalUsdValue
	}
	return ""
}

func (m *QueryUserCollateralResponse) GetWithdrawableUsd() string {
	if m != nil {
		return m.WithdrawableUsd
	}
	return ""
}

type QueryAllowedAssetsRequest struct {
}

func (m *QueryAllowedAssetsRequest) Reset()         { *m = QueryAllowedAssetsRequest{} }
func (m *QueryAllowedAssetsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllowedAssetsRequest) ProtoMessage()    {}
func (*QueryAllowedAssetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_331dea947f6bd23d, []int{5}
}
func (m *QueryAllowedAssetsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllowedAssetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllowedAssetsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllowedAssetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllowedAssetsRequest.Merge(m, src)
}
func (m *QueryAllowedAssetsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllowedAssetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllowedAssetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllowedAssetsRequest proto.InternalMessageInfo

type QueryAllowedAssetsResponse struct {
	AllowedAssets []*AllowedAsset `protobuf:"bytes,1,rep,name=allowed_assets,json=allowedAssets,proto3" json:"allowed_assets,omitempty"`
}

func (m *QueryAllowedAssetsResponse) Reset()         { *m = QueryAllowedAssetsResponse{} }
func (m *QueryAllowedAssetsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllowedAssetsResponse) ProtoMessage()    {}
func (*QueryAllowedAssetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_331dea947f6bd23d, []int{6}
}
func (m *QueryAllowedAssetsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllowedAssetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllowedAssetsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllowedAssetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllowedAssetsResponse.Merge(m, src)
}
func (m *QueryAllowedAssetsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllowedAssetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllowedAssetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllowedAssetsResponse proto.InternalMessageInfo

func (m *QueryAllowedAssetsResponse) GetAllowedAssets() []*AllowedAsset {
	if m != nil {
		return m.AllowedAssets
	}
	return nil
}

type QueryModuleBalanceRequest struct {
}

func (m *QueryModuleBalanceRequest) Reset()         { *m = QueryModuleBalanceRequest{} }
func (m *QueryModuleBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryModuleBalanceRequest) ProtoMessage()    {}
func (*QueryModuleBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_331dea947f6bd23d, []int{7}
}
func (m *QueryModuleBalanceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryModuleBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryModuleBalanceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryModuleBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryModuleBalanceRequest.Merge(m, src)
}
func (m *QueryModuleBalanceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryModuleBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryModuleBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryModuleBalanceRequest proto.InternalMessageInfo

type QueryModuleBalanceResponse struct {
	Balance []*types.Coin `protobuf:"bytes,1,rep,name=balance,proto3" json:"balance,omitempty"`
}

func (m *QueryModuleBalanceResponse) Reset()         { *m = QueryModuleBalanceResponse{} }
func (m *QueryModuleBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryModuleBalanceResponse) ProtoMessage()    {}
func (*QueryModuleBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_331dea947f6bd23d, []int{8}
}
func (m *QueryModuleBalanceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryModuleBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryModuleBalanceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryModuleBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryModuleBalanceResponse.Merge(m, src)
}
func (m *QueryModuleBalanceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryModuleBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryModuleBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryModuleBalanceResponse proto.InternalMessageInfo

func (m *QueryModuleBalanceResponse) GetBalance() []*types.Coin {
	if m != nil {
		return m.Balance
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryCollateralParamsRequest)(nil), "symphony.collateral.v1beta1.QueryCollateralParamsRequest")
	proto.RegisterType((*QueryCollateralParamsResponse)(nil), "symphony.collateral.v1beta1.QueryCollateralParamsResponse")
	proto.RegisterType((*QueryUserCollateralRequest)(nil), "symphony.collateral.v1beta1.QueryUserCollateralRequest")
	proto.RegisterType((*UserAssetPosition)(nil), "symphony.collateral.v1beta1.UserAssetPosition")
	proto.RegisterType((*QueryUserCollateralResponse)(nil), "symphony.collateral.v1beta1.QueryUserCollateralResponse")
	proto.RegisterType((*QueryAllowedAssetsRequest)(nil), "symphony.collateral.v1beta1.QueryAllowedAssetsRequest")
	proto.RegisterType((*QueryAllowedAssetsResponse)(nil), "symphony.collateral.v1beta1.QueryAllowedAssetsResponse")
	proto.RegisterType((*QueryModuleBalanceRequest)(nil), "symphony.collateral.v1beta1.QueryModuleBalanceRequest")
	proto.RegisterType((*QueryModuleBalanceResponse)(nil), "symphony.collateral.v1beta1.QueryModuleBalanceResponse")
}

func init() {
	proto.RegisterFile("symphony/collateral/v1beta1/query.proto", fileDescriptor_331dea947f6bd23d)
}

var fileDescriptor_331dea947f6bd23d = []byte{
	// 672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0x4d, 0x4f, 0xd4, 0x40,
	0x18, 0xc7, 0x29, 0x08, 0xca, 0x90, 0x05, 0x9c, 0x98, 0x08, 0x5d, 0x6c, 0x4c, 0x51, 0x84, 0x80,
	0x1d, 0x77, 0x49, 0xc0, 0x97, 0x13, 0x70, 0xd5, 0x64, 0xd9, 0x04, 0x0f, 0xc6, 0x64, 0x33, 0xdd,
	0x8e, 0xa5, 0xc9, 0x6c, 0xa7, 0x74, 0xa6, 0x0b, 0x1b, 0xe3, 0xc5, 0x4f, 0x60, 0xe2, 0xe7, 0xd0,
	0xa3, 0x47, 0xcf, 0x1e, 0x49, 0xbc, 0x18, 0x4f, 0x86, 0xf5, 0x83, 0x98, 0x99, 0x4e, 0xbb, 0x2f,
	0xae, 0x85, 0xf5, 0xb4, 0x9d, 0xe7, 0xff, 0xbc, 0xfc, 0x9e, 0x67, 0x9e, 0xc9, 0x82, 0x07, 0xbc,
	0xd3, 0x8a, 0x8e, 0x59, 0xd8, 0x41, 0x4d, 0x46, 0x29, 0x16, 0x24, 0xc6, 0x14, 0xb5, 0x2b, 0x2e,
	0x11, 0xb8, 0x82, 0x4e, 0x12, 0x12, 0x77, 0x9c, 0x28, 0x66, 0x82, 0xc1, 0x72, 0xe6, 0xe8, 0xf4,
	0x1c, 0x1d, 0xed, 0x68, 0x5a, 0x4d, 0xc6, 0x5b, 0x8c, 0x23, 0x17, 0x73, 0x92, 0x47, 0x37, 0x59,
	0x10, 0xa6, 0xc1, 0xa6, 0xa9, 0x75, 0x71, 0x96, 0xab, 0xe2, 0x4c, 0x6b, 0xcb, 0x3e, 0x63, 0x3e,
	0x25, 0x48, 0x9d, 0xdc, 0xe4, 0x0d, 0xc2, 0x61, 0x27, 0x93, 0xd2, 0xb0, 0x86, 0x3a, 0xa1, 0xf4,
	0xa0, 0xa5, 0x5b, 0x3e, 0xf3, 0x59, 0x6a, 0x97, 0x5f, 0xda, 0xba, 0xa2, 0x73, 0xe1, 0x28, 0x40,
	0x38, 0x0c, 0x99, 0xc0, 0x22, 0x60, 0x61, 0x16, 0x73, 0x5b, 0x53, 0xb4, 0xb8, 0x8f, 0xda, 0x15,
	0xf9, 0xa3, 0x85, 0xad, 0xa2, 0x21, 0xf4, 0xb5, 0xab, 0xbc, 0x6d, 0x0b, 0xac, 0x1c, 0xca, 0xc1,
	0x1c, 0xe4, 0x42, 0x0d, 0xc7, 0xb8, 0xc5, 0xeb, 0xe4, 0x24, 0x21, 0x5c, 0xd8, 0xaf, 0xc1, 0x9d,
	0x7f, 0xe8, 0x3c, 0x62, 0x21, 0x27, 0xf0, 0x19, 0x98, 0x89, 0x94, 0x65, 0xc9, 0xb8, 0x6b, 0xac,
	0xcf, 0x55, 0x57, 0x9d, 0x82, 0xd9, 0x3a, 0x3a, 0x58, 0x87, 0xd8, 0x8f, 0x80, 0xa9, 0xb2, 0x1f,
	0x71, 0x12, 0xf7, 0x2a, 0xe8, 0xda, 0x10, 0x82, 0x6b, 0x09, 0x27, 0xb1, 0x4a, 0x3c, 0x5b, 0x57,
	0xdf, 0x36, 0x06, 0x37, 0xa5, 0xf3, 0x1e, 0xe7, 0x44, 0xd4, 0x18, 0x0f, 0xe4, 0x48, 0x20, 0x02,
	0xd3, 0x58, 0x1a, 0x34, 0xc2, 0xb2, 0xa3, 0xa7, 0x2b, 0x6f, 0x30, 0x2f, 0x7d, 0xc0, 0x82, 0xb0,
	0x9e, 0xfa, 0xc1, 0x32, 0x98, 0x4d, 0xb8, 0xd7, 0x68, 0x63, 0x9a, 0x90, 0xa5, 0x49, 0x95, 0xfe,
	0x46, 0xc2, 0xbd, 0x97, 0xf2, 0x6c, 0x7f, 0x35, 0x40, 0x79, 0x24, 0x95, 0xee, 0xf8, 0x39, 0x98,
	0x8d, 0x74, 0x65, 0xd9, 0xf4, 0xd4, 0xfa, 0x5c, 0xd5, 0x29, 0x6c, 0xfa, 0x2f, 0xe0, 0x7a, 0x2f,
	0x01, 0x5c, 0x03, 0x0b, 0x82, 0x09, 0x4c, 0x1b, 0xc3, 0x40, 0x25, 0x65, 0x3e, 0xd2, 0x54, 0x70,
	0x03, 0x2c, 0x9e, 0x06, 0xe2, 0xd8, 0x8b, 0xf1, 0x29, 0x76, 0x29, 0x91, 0xee, 0x4b, 0x53, 0xca,
	0x71, 0xa1, 0xdf, 0x7e, 0xc4, 0x3d, 0xbb, 0x0c, 0x96, 0x15, 0xff, 0x1e, 0xa5, 0xec, 0x94, 0x78,
	0xaa, 0x74, 0x7e, 0xa1, 0xa1, 0x1e, 0xf9, 0x90, 0xa8, 0x7b, 0xab, 0x81, 0x79, 0x9c, 0x0a, 0x0d,
	0x35, 0xa9, 0xac, 0xc1, 0x8d, 0xc2, 0x06, 0xfb, 0x73, 0xd5, 0x4b, 0xb8, 0x3f, 0x73, 0x0e, 0xf3,
	0x82, 0x79, 0x09, 0x25, 0xfb, 0x98, 0xe2, 0xb0, 0x49, 0x32, 0x98, 0x43, 0x0d, 0x33, 0x24, 0x6a,
	0x98, 0x6d, 0x70, 0xdd, 0x4d, 0x4d, 0x9a, 0xa2, 0xe0, 0x62, 0x33, 0xcf, 0xea, 0xcf, 0x69, 0x30,
	0xad, 0x72, 0xc2, 0x2f, 0x06, 0x58, 0x1c, 0x5e, 0x5b, 0xf8, 0xa4, 0xb0, 0x91, 0xa2, 0xa7, 0x60,
	0x3e, 0xfd, 0x9f, 0xd0, 0xb4, 0x15, 0x7b, 0xf3, 0xfd, 0xf7, 0xdf, 0x1f, 0x27, 0xef, 0xc3, 0x55,
	0x54, 0xf4, 0x3a, 0xd3, 0x57, 0x21, 0xc1, 0xe7, 0x07, 0x77, 0x0f, 0xee, 0x5e, 0x5e, 0x7b, 0xe4,
	0x1b, 0x32, 0x1f, 0x8f, 0x1f, 0xa8, 0x91, 0x2b, 0x0a, 0x79, 0x13, 0x6e, 0x14, 0x22, 0xcb, 0x47,
	0xc9, 0xd1, 0x5b, 0xf9, 0xf3, 0x0e, 0x7e, 0x32, 0x40, 0x69, 0x60, 0xaf, 0xe0, 0xce, 0xe5, 0xe5,
	0x47, 0x6d, 0xa9, 0xb9, 0x3b, 0x76, 0xdc, 0x58, 0x83, 0x4e, 0x77, 0x1b, 0x7e, 0x36, 0x40, 0x69,
	0x60, 0xf5, 0xae, 0xc2, 0x3b, 0x6a, 0x91, 0xaf, 0xc2, 0x3b, 0x72, 0xc7, 0xed, 0x2d, 0xc5, 0xbb,
	0x06, 0xef, 0x15, 0xf2, 0xea, 0xe5, 0xde, 0xaf, 0x7d, 0xbb, 0xb0, 0x8c, 0xf3, 0x0b, 0xcb, 0xf8,
	0x75, 0x61, 0x19, 0x1f, 0xba, 0xd6, 0xc4, 0x79, 0xd7, 0x9a, 0xf8, 0xd1, 0xb5, 0x26, 0x5e, 0xed,
	0xf8, 0x81, 0x38, 0x4e, 0x5c, 0xa7, 0xc9, 0x5a, 0x48, 0xbd, 0x91, 0x80, 0x3f, 0xa4, 0xd8, 0xe5,
	0xd9, 0x01, 0xb5, 0xab, 0xbb, 0xe8, 0xac, 0x3f, 0xb7, 0xe8, 0x44, 0x84, 0xbb, 0x33, 0xea, 0x6f,
	0x60, 0xfb, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x38, 0x11, 0x82, 0x3b, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	CollateralParams(ctx context.Context, in *QueryCollateralParamsRequest, opts ...grpc.CallOption) (*QueryCollateralParamsResponse, error)
	// Get all user collateral positions
	UserCollateral(ctx context.Context, in *QueryUserCollateralRequest, opts ...grpc.CallOption) (*QueryUserCollateralResponse, error)
	// List allowed assets
	AllowedAssets(ctx context.Context, in *QueryAllowedAssetsRequest, opts ...grpc.CallOption) (*QueryAllowedAssetsResponse, error)
	// Current balance of module account
	ModuleBalance(ctx context.Context, in *QueryModuleBalanceRequest, opts ...grpc.CallOption) (*QueryModuleBalanceResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) CollateralParams(ctx context.Context, in *QueryCollateralParamsRequest, opts ...grpc.CallOption) (*QueryCollateralParamsResponse, error) {
	out := new(QueryCollateralParamsResponse)
	err := c.cc.Invoke(ctx, "/symphony.collateral.v1beta1.Query/CollateralParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserCollateral(ctx context.Context, in *QueryUserCollateralRequest, opts ...grpc.CallOption) (*QueryUserCollateralResponse, error) {
	out := new(QueryUserCollateralResponse)
	err := c.cc.Invoke(ctx, "/symphony.collateral.v1beta1.Query/UserCollateral", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllowedAssets(ctx context.Context, in *QueryAllowedAssetsRequest, opts ...grpc.CallOption) (*QueryAllowedAssetsResponse, error) {
	out := new(QueryAllowedAssetsResponse)
	err := c.cc.Invoke(ctx, "/symphony.collateral.v1beta1.Query/AllowedAssets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ModuleBalance(ctx context.Context, in *QueryModuleBalanceRequest, opts ...grpc.CallOption) (*QueryModuleBalanceResponse, error) {
	out := new(QueryModuleBalanceResponse)
	err := c.cc.Invoke(ctx, "/symphony.collateral.v1beta1.Query/ModuleBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	CollateralParams(context.Context, *QueryCollateralParamsRequest) (*QueryCollateralParamsResponse, error)
	// Get all user collateral positions
	UserCollateral(context.Context, *QueryUserCollateralRequest) (*QueryUserCollateralResponse, error)
	// List allowed assets
	AllowedAssets(context.Context, *QueryAllowedAssetsRequest) (*QueryAllowedAssetsResponse, error)
	// Current balance of module account
	ModuleBalance(context.Context, *QueryModuleBalanceRequest) (*QueryModuleBalanceResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) CollateralParams(ctx context.Context, req *QueryCollateralParamsRequest) (*QueryCollateralParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollateralParams not implemented")
}
func (*UnimplementedQueryServer) UserCollateral(ctx context.Context, req *QueryUserCollateralRequest) (*QueryUserCollateralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCollateral not implemented")
}
func (*UnimplementedQueryServer) AllowedAssets(ctx context.Context, req *QueryAllowedAssetsRequest) (*QueryAllowedAssetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllowedAssets not implemented")
}
func (*UnimplementedQueryServer) ModuleBalance(ctx context.Context, req *QueryModuleBalanceRequest) (*QueryModuleBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModuleBalance not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_CollateralParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCollateralParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CollateralParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/symphony.collateral.v1beta1.Query/CollateralParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CollateralParams(ctx, req.(*QueryCollateralParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserCollateral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserCollateralRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserCollateral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/symphony.collateral.v1beta1.Query/UserCollateral",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserCollateral(ctx, req.(*QueryUserCollateralRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllowedAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllowedAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllowedAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/symphony.collateral.v1beta1.Query/AllowedAssets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllowedAssets(ctx, req.(*QueryAllowedAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ModuleBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryModuleBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ModuleBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/symphony.collateral.v1beta1.Query/ModuleBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ModuleBalance(ctx, req.(*QueryModuleBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "symphony.collateral.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CollateralParams",
			Handler:    _Query_CollateralParams_Handler,
		},
		{
			MethodName: "UserCollateral",
			Handler:    _Query_UserCollateral_Handler,
		},
		{
			MethodName: "AllowedAssets",
			Handler:    _Query_AllowedAssets_Handler,
		},
		{
			MethodName: "ModuleBalance",
			Handler:    _Query_ModuleBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "symphony/collateral/v1beta1/query.proto",
}

func (m *QueryCollateralParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCollateralParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCollateralParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryCollateralParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCollateralParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCollateralParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserCollateralRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserCollateralRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserCollateralRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.User) > 0 {
		i -= len(m.User)
		copy(dAtA[i:], m.User)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.User)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UserAssetPosition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserAssetPosition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserAssetPosition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UsdValue) > 0 {
		i -= len(m.UsdValue)
		copy(dAtA[i:], m.UsdValue)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.UsdValue)))
		i--
		dAtA[i] = 0x12
	}
	if m.Asset != nil {
		{
			size, err := m.Asset.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserCollateralResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserCollateralResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserCollateralResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WithdrawableUsd) > 0 {
		i -= len(m.WithdrawableUsd)
		copy(dAtA[i:], m.WithdrawableUsd)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.WithdrawableUsd)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TotalUsdValue) > 0 {
		i -= len(m.TotalUsdValue)
		copy(dAtA[i:], m.TotalUsdValue)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TotalUsdValue)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Positions) > 0 {
		for iNdEx := len(m.Positions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Positions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllowedAssetsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllowedAssetsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllowedAssetsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAllowedAssetsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllowedAssetsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllowedAssetsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AllowedAssets) > 0 {
		for iNdEx := len(m.AllowedAssets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AllowedAssets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryModuleBalanceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryModuleBalanceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryModuleBalanceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryModuleBalanceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryModuleBalanceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryModuleBalanceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Balance) > 0 {
		for iNdEx := len(m.Balance) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Balance[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryCollateralParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryCollateralParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryUserCollateralRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *UserAssetPosition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Asset != nil {
		l = m.Asset.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.UsdValue)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryUserCollateralResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Positions) > 0 {
		for _, e := range m.Positions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	l = len(m.TotalUsdValue)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.WithdrawableUsd)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllowedAssetsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAllowedAssetsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AllowedAssets) > 0 {
		for _, e := range m.AllowedAssets {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryModuleBalanceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryModuleBalanceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Balance) > 0 {
		for _, e := range m.Balance {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryCollateralParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCollateralParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCollateralParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCollateralParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCollateralParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCollateralParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserCollateralRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserCollateralRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserCollateralRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserAssetPosition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserAssetPosition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserAssetPosition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Asset == nil {
				m.Asset = &types.Coin{}
			}
			if err := m.Asset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UsdValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UsdValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserCollateralResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserCollateralResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserCollateralResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Positions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Positions = append(m.Positions, &UserAssetPosition{})
			if err := m.Positions[len(m.Positions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalUsdValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalUsdValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawableUsd", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawableUsd = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllowedAssetsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllowedAssetsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllowedAssetsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllowedAssetsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllowedAssetsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllowedAssetsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedAssets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedAssets = append(m.AllowedAssets, &AllowedAsset{})
			if err := m.AllowedAssets[len(m.AllowedAssets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryModuleBalanceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryModuleBalanceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryModuleBalanceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryModuleBalanceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryModuleBalanceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryModuleBalanceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Balance = append(m.Balance, &types.Coin{})
			if err := m.Balance[len(m.Balance)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
