// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: symphony/stakeibc/ica_account.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ICAAccountType int32

const (
	ICAAccountType_DELEGATION             ICAAccountType = 0
	ICAAccountType_FEE                    ICAAccountType = 1
	ICAAccountType_WITHDRAWAL             ICAAccountType = 2
	ICAAccountType_REDEMPTION             ICAAccountType = 3
	ICAAccountType_COMMUNITY_POOL_DEPOSIT ICAAccountType = 4
	ICAAccountType_COMMUNITY_POOL_RETURN  ICAAccountType = 5
	ICAAccountType_CONVERTER_UNWIND       ICAAccountType = 6
	ICAAccountType_CONVERTER_TRADE        ICAAccountType = 7
)

var ICAAccountType_name = map[int32]string{
	0: "DELEGATION",
	1: "FEE",
	2: "WITHDRAWAL",
	3: "REDEMPTION",
	4: "COMMUNITY_POOL_DEPOSIT",
	5: "COMMUNITY_POOL_RETURN",
	6: "CONVERTER_UNWIND",
	7: "CONVERTER_TRADE",
}

var ICAAccountType_value = map[string]int32{
	"DELEGATION":             0,
	"FEE":                    1,
	"WITHDRAWAL":             2,
	"REDEMPTION":             3,
	"COMMUNITY_POOL_DEPOSIT": 4,
	"COMMUNITY_POOL_RETURN":  5,
	"CONVERTER_UNWIND":       6,
	"CONVERTER_TRADE":        7,
}

func (x ICAAccountType) String() string {
	return proto.EnumName(ICAAccountType_name, int32(x))
}

func (ICAAccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d44194790bb46fd3, []int{0}
}

type ICAAccount struct {
	ChainId      string         `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Type         ICAAccountType `protobuf:"varint,2,opt,name=type,proto3,enum=symphony.stakeibc.ICAAccountType" json:"type,omitempty"`
	ConnectionId string         `protobuf:"bytes,3,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Address      string         `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *ICAAccount) Reset()         { *m = ICAAccount{} }
func (m *ICAAccount) String() string { return proto.CompactTextString(m) }
func (*ICAAccount) ProtoMessage()    {}
func (*ICAAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_d44194790bb46fd3, []int{0}
}
func (m *ICAAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ICAAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ICAAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ICAAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ICAAccount.Merge(m, src)
}
func (m *ICAAccount) XXX_Size() int {
	return m.Size()
}
func (m *ICAAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_ICAAccount.DiscardUnknown(m)
}

var xxx_messageInfo_ICAAccount proto.InternalMessageInfo

func (m *ICAAccount) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *ICAAccount) GetType() ICAAccountType {
	if m != nil {
		return m.Type
	}
	return ICAAccountType_DELEGATION
}

func (m *ICAAccount) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *ICAAccount) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterEnum("symphony.stakeibc.ICAAccountType", ICAAccountType_name, ICAAccountType_value)
	proto.RegisterType((*ICAAccount)(nil), "symphony.stakeibc.ICAAccount")
}

func init() {
	proto.RegisterFile("symphony/stakeibc/ica_account.proto", fileDescriptor_d44194790bb46fd3)
}

var fileDescriptor_d44194790bb46fd3 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcf, 0x8e, 0xd2, 0x40,
	0x18, 0xc0, 0x3b, 0x80, 0x54, 0x27, 0x8a, 0xe3, 0xf8, 0x27, 0xc5, 0x43, 0x83, 0x72, 0x21, 0x26,
	0xb6, 0x09, 0x6a, 0x3c, 0x57, 0x3a, 0xea, 0x24, 0xd0, 0x92, 0x71, 0x90, 0xe8, 0xa5, 0x69, 0xa7,
	0x8d, 0x34, 0x4a, 0xa7, 0x61, 0x8a, 0xd9, 0xbe, 0xc5, 0xbe, 0xc0, 0x3e, 0xc1, 0xbe, 0xc8, 0x1e,
	0x39, 0xee, 0x71, 0x03, 0x2f, 0xb2, 0xa1, 0x2c, 0x69, 0x76, 0xf7, 0xf8, 0xfb, 0xbe, 0x5f, 0x7e,
	0x93, 0xcc, 0x07, 0xfb, 0xaa, 0x5c, 0xe6, 0x0b, 0x99, 0x95, 0xb6, 0x2a, 0xc2, 0xbf, 0x49, 0x1a,
	0x09, 0x3b, 0x15, 0x61, 0x10, 0x0a, 0x21, 0xd7, 0x59, 0x61, 0xe5, 0x2b, 0x59, 0x48, 0xfc, 0xec,
	0x28, 0x59, 0x47, 0xe9, 0xed, 0x19, 0x80, 0x90, 0x8e, 0x1c, 0xe7, 0xe0, 0xe1, 0x2e, 0x7c, 0x28,
	0x16, 0x61, 0x9a, 0x05, 0x69, 0x6c, 0x80, 0x1e, 0x18, 0x3c, 0x62, 0x7a, 0xc5, 0x34, 0xc6, 0x9f,
	0x60, 0xab, 0x28, 0xf3, 0xc4, 0x68, 0xf4, 0xc0, 0xa0, 0x33, 0x7c, 0x63, 0xdd, 0x6b, 0x59, 0x75,
	0x87, 0x97, 0x79, 0xc2, 0x2a, 0x1d, 0xf7, 0xe1, 0x13, 0x21, 0xb3, 0x2c, 0x11, 0x45, 0x2a, 0xab,
	0x6c, 0xb3, 0xca, 0x3e, 0xae, 0x87, 0x34, 0xc6, 0x06, 0xd4, 0xc3, 0x38, 0x5e, 0x25, 0x4a, 0x19,
	0xad, 0xc3, 0xab, 0x37, 0xf8, 0xee, 0x1c, 0xc0, 0xce, 0xed, 0x2e, 0xee, 0x40, 0xe8, 0x92, 0x31,
	0xf9, 0xe6, 0x70, 0xea, 0x7b, 0x48, 0xc3, 0x3a, 0x6c, 0x7e, 0x25, 0x04, 0x81, 0xfd, 0x62, 0x4e,
	0xf9, 0x77, 0x97, 0x39, 0x73, 0x67, 0x8c, 0x1a, 0x7b, 0x66, 0xc4, 0x25, 0x93, 0x69, 0x25, 0x36,
	0xf1, 0x6b, 0xf8, 0x6a, 0xe4, 0x4f, 0x26, 0x33, 0x8f, 0xf2, 0x5f, 0xc1, 0xd4, 0xf7, 0xc7, 0x81,
	0x4b, 0xa6, 0xfe, 0x0f, 0xca, 0x51, 0x0b, 0x77, 0xe1, 0xcb, 0x3b, 0x3b, 0x46, 0xf8, 0x8c, 0x79,
	0xe8, 0x01, 0x7e, 0x01, 0xd1, 0xc8, 0xf7, 0x7e, 0x12, 0xc6, 0x09, 0x0b, 0x66, 0xde, 0x9c, 0x7a,
	0x2e, 0x6a, 0xe3, 0xe7, 0xf0, 0x69, 0x3d, 0xe5, 0xcc, 0x71, 0x09, 0xd2, 0xbf, 0x78, 0x17, 0x5b,
	0x13, 0x6c, 0xb6, 0x26, 0xb8, 0xda, 0x9a, 0xe0, 0x74, 0x67, 0x6a, 0x9b, 0x9d, 0xa9, 0x5d, 0xee,
	0x4c, 0xed, 0xf7, 0xc7, 0x3f, 0x69, 0xb1, 0x58, 0x47, 0x96, 0x90, 0x4b, 0x5b, 0xaa, 0xa5, 0x54,
	0xa9, 0x7a, 0xff, 0x2f, 0x8c, 0xd4, 0x11, 0xec, 0xff, 0xc3, 0xcf, 0xf6, 0x49, 0x7d, 0xbc, 0xfd,
	0xdf, 0xa9, 0xa8, 0x5d, 0xdd, 0xed, 0xc3, 0x75, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2a, 0xfd, 0xef,
	0x98, 0xde, 0x01, 0x00, 0x00,
}

func (m *ICAAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ICAAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ICAAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintIcaAccount(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ConnectionId) > 0 {
		i -= len(m.ConnectionId)
		copy(dAtA[i:], m.ConnectionId)
		i = encodeVarintIcaAccount(dAtA, i, uint64(len(m.ConnectionId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Type != 0 {
		i = encodeVarintIcaAccount(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintIcaAccount(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintIcaAccount(dAtA []byte, offset int, v uint64) int {
	offset -= sovIcaAccount(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ICAAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovIcaAccount(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovIcaAccount(uint64(m.Type))
	}
	l = len(m.ConnectionId)
	if l > 0 {
		n += 1 + l + sovIcaAccount(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovIcaAccount(uint64(l))
	}
	return n
}

func sovIcaAccount(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIcaAccount(x uint64) (n int) {
	return sovIcaAccount(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ICAAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIcaAccount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ICAAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ICAAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIcaAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIcaAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIcaAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIcaAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= ICAAccountType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIcaAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIcaAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIcaAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIcaAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIcaAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIcaAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIcaAccount(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIcaAccount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIcaAccount(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIcaAccount
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIcaAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIcaAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIcaAccount
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIcaAccount
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIcaAccount
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIcaAccount        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIcaAccount          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIcaAccount = fmt.Errorf("proto: unexpected end of group")
)
