// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: symphony/stablestaking/v1beta1/stablestaking.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/cosmos/gogoproto/types"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	RewardRate               string        `protobuf:"bytes,1,opt,name=reward_rate,json=rewardRate,proto3" json:"reward_rate,omitempty"`
	UnbondingDuration        time.Duration `protobuf:"bytes,2,opt,name=unbonding_duration,json=unbondingDuration,proto3,stdduration" json:"unbonding_duration"`
	SupportedTokens          []string      `protobuf:"bytes,3,rep,name=supported_tokens,json=supportedTokens,proto3" json:"supported_tokens,omitempty"`
	RewardEpochIdentifier    string        `protobuf:"bytes,4,opt,name=reward_epoch_identifier,json=rewardEpochIdentifier,proto3" json:"reward_epoch_identifier,omitempty"`
	UnbondingEpochIdentifier string        `protobuf:"bytes,5,opt,name=unbonding_epoch_identifier,json=unbondingEpochIdentifier,proto3" json:"unbonding_epoch_identifier,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ae0713c4e1380de, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetRewardRate() string {
	if m != nil {
		return m.RewardRate
	}
	return ""
}

func (m *Params) GetUnbondingDuration() time.Duration {
	if m != nil {
		return m.UnbondingDuration
	}
	return 0
}

func (m *Params) GetSupportedTokens() []string {
	if m != nil {
		return m.SupportedTokens
	}
	return nil
}

func (m *Params) GetRewardEpochIdentifier() string {
	if m != nil {
		return m.RewardEpochIdentifier
	}
	return ""
}

func (m *Params) GetUnbondingEpochIdentifier() string {
	if m != nil {
		return m.UnbondingEpochIdentifier
	}
	return ""
}

type GenesisState struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ae0713c4e1380de, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type StakingPool struct {
	Denom       string                      `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	TotalStaked cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=total_staked,json=totalStaked,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"total_staked" yaml:"total_staked"`
	TotalShares cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=total_shares,json=totalShares,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"total_shares" yaml:"total_shares"`
}

func (m *StakingPool) Reset()         { *m = StakingPool{} }
func (m *StakingPool) String() string { return proto.CompactTextString(m) }
func (*StakingPool) ProtoMessage()    {}
func (*StakingPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ae0713c4e1380de, []int{2}
}
func (m *StakingPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StakingPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StakingPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StakingPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakingPool.Merge(m, src)
}
func (m *StakingPool) XXX_Size() int {
	return m.Size()
}
func (m *StakingPool) XXX_DiscardUnknown() {
	xxx_messageInfo_StakingPool.DiscardUnknown(m)
}

var xxx_messageInfo_StakingPool proto.InternalMessageInfo

func (m *StakingPool) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type UserStake struct {
	Address string                      `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Shares  cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=shares,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"shares" yaml:"shares"`
	Epoch   int64                       `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (m *UserStake) Reset()         { *m = UserStake{} }
func (m *UserStake) String() string { return proto.CompactTextString(m) }
func (*UserStake) ProtoMessage()    {}
func (*UserStake) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ae0713c4e1380de, []int{3}
}
func (m *UserStake) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserStake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserStake.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserStake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStake.Merge(m, src)
}
func (m *UserStake) XXX_Size() int {
	return m.Size()
}
func (m *UserStake) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStake.DiscardUnknown(m)
}

var xxx_messageInfo_UserStake proto.InternalMessageInfo

func (m *UserStake) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserStake) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

type UnbondingInfo struct {
	Address     string                      `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount      cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=amount,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"amount" yaml:"amount"`
	Denom       string                      `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	UnbondEpoch int64                       `protobuf:"varint,4,opt,name=unbond_epoch,json=unbondEpoch,proto3" json:"unbond_epoch,omitempty"`
}

func (m *UnbondingInfo) Reset()         { *m = UnbondingInfo{} }
func (m *UnbondingInfo) String() string { return proto.CompactTextString(m) }
func (*UnbondingInfo) ProtoMessage()    {}
func (*UnbondingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ae0713c4e1380de, []int{4}
}
func (m *UnbondingInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UnbondingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UnbondingInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UnbondingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbondingInfo.Merge(m, src)
}
func (m *UnbondingInfo) XXX_Size() int {
	return m.Size()
}
func (m *UnbondingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbondingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UnbondingInfo proto.InternalMessageInfo

func (m *UnbondingInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UnbondingInfo) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *UnbondingInfo) GetUnbondEpoch() int64 {
	if m != nil {
		return m.UnbondEpoch
	}
	return 0
}

type EpochSnapshot struct {
	TotalStaked cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=total_staked,json=totalStaked,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"total_staked" yaml:"total_staked"`
	TotalShares cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=total_shares,json=totalShares,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"total_shares" yaml:"total_shares"`
	Stakers     []*UserStake                `protobuf:"bytes,3,rep,name=stakers,proto3" json:"stakers,omitempty"`
}

func (m *EpochSnapshot) Reset()         { *m = EpochSnapshot{} }
func (m *EpochSnapshot) String() string { return proto.CompactTextString(m) }
func (*EpochSnapshot) ProtoMessage()    {}
func (*EpochSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ae0713c4e1380de, []int{5}
}
func (m *EpochSnapshot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochSnapshot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochSnapshot.Merge(m, src)
}
func (m *EpochSnapshot) XXX_Size() int {
	return m.Size()
}
func (m *EpochSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_EpochSnapshot proto.InternalMessageInfo

func (m *EpochSnapshot) GetStakers() []*UserStake {
	if m != nil {
		return m.Stakers
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "symphony.stablestaking.v1beta1.Params")
	proto.RegisterType((*GenesisState)(nil), "symphony.stablestaking.v1beta1.GenesisState")
	proto.RegisterType((*StakingPool)(nil), "symphony.stablestaking.v1beta1.StakingPool")
	proto.RegisterType((*UserStake)(nil), "symphony.stablestaking.v1beta1.UserStake")
	proto.RegisterType((*UnbondingInfo)(nil), "symphony.stablestaking.v1beta1.UnbondingInfo")
	proto.RegisterType((*EpochSnapshot)(nil), "symphony.stablestaking.v1beta1.EpochSnapshot")
}

func init() {
	proto.RegisterFile("symphony/stablestaking/v1beta1/stablestaking.proto", fileDescriptor_7ae0713c4e1380de)
}

var fileDescriptor_7ae0713c4e1380de = []byte{
	// 649 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x8d, 0x93, 0x36, 0xfd, 0x3a, 0x4e, 0xf5, 0xc1, 0x50, 0x44, 0x5a, 0x24, 0xa7, 0x78, 0x81,
	0xda, 0x05, 0xb6, 0x1a, 0x10, 0x88, 0x8a, 0x55, 0x28, 0x42, 0x95, 0xba, 0xa8, 0x9c, 0x76, 0x83,
	0x84, 0xa2, 0x71, 0x3c, 0xb5, 0xad, 0xda, 0x73, 0xad, 0x99, 0x71, 0x21, 0x8f, 0xc0, 0x0e, 0xb1,
	0x62, 0xc5, 0x33, 0xf0, 0x18, 0x5d, 0x76, 0x89, 0x58, 0x14, 0x68, 0xdf, 0x80, 0x27, 0x40, 0x9e,
	0xb1, 0xdd, 0x3f, 0xa9, 0xa0, 0x0a, 0x76, 0x3e, 0xf7, 0xce, 0x39, 0x73, 0x7c, 0xee, 0xb5, 0x51,
	0x5f, 0x4c, 0xd2, 0x2c, 0x02, 0x36, 0x71, 0x85, 0x24, 0x7e, 0x42, 0x85, 0x24, 0x7b, 0x31, 0x0b,
	0xdd, 0xfd, 0x55, 0x9f, 0x4a, 0xb2, 0x7a, 0xbe, 0xea, 0x64, 0x1c, 0x24, 0x60, 0xab, 0xe2, 0x38,
	0xe7, 0xbb, 0x25, 0x67, 0x71, 0x61, 0x0c, 0x22, 0x05, 0x31, 0x52, 0xa7, 0x5d, 0x0d, 0x34, 0x75,
	0x71, 0x3e, 0x84, 0x10, 0x74, 0xbd, 0x78, 0x2a, 0xab, 0x56, 0x08, 0x10, 0x26, 0xd4, 0x55, 0xc8,
	0xcf, 0x77, 0xdd, 0x20, 0xe7, 0x44, 0xc6, 0xc0, 0xaa, 0xbe, 0xd6, 0x70, 0x7d, 0x22, 0x68, 0xed,
	0x6c, 0x0c, 0x71, 0xd9, 0xb7, 0x3f, 0x35, 0x51, 0x7b, 0x8b, 0x70, 0x92, 0x0a, 0xdc, 0x43, 0x26,
	0xa7, 0x6f, 0x08, 0x0f, 0x46, 0x9c, 0x48, 0xda, 0x35, 0x96, 0x8c, 0xe5, 0x59, 0x0f, 0xe9, 0x92,
	0x47, 0x24, 0xc5, 0x1e, 0xc2, 0x39, 0xf3, 0x81, 0x05, 0x31, 0x0b, 0x47, 0xd5, 0x3d, 0xdd, 0xe6,
	0x92, 0xb1, 0x6c, 0xf6, 0x17, 0x1c, 0x6d, 0xc4, 0xa9, 0x8c, 0x38, 0xeb, 0xe5, 0x81, 0xc1, 0x7f,
	0x07, 0x47, 0xbd, 0xc6, 0xc7, 0x6f, 0x3d, 0xc3, 0xbb, 0x59, 0xd3, 0xab, 0x26, 0x5e, 0x41, 0x37,
	0x44, 0x9e, 0x65, 0xc0, 0x25, 0x0d, 0x46, 0x12, 0xf6, 0x28, 0x13, 0xdd, 0xd6, 0x52, 0x6b, 0x79,
	0xd6, 0xfb, 0xbf, 0xae, 0x6f, 0xab, 0x32, 0x7e, 0x8c, 0xee, 0x94, 0xfe, 0x68, 0x06, 0xe3, 0x68,
	0x14, 0x07, 0x94, 0xc9, 0x78, 0x37, 0xa6, 0xbc, 0x3b, 0xa5, 0xbc, 0xde, 0xd6, 0xed, 0x17, 0x45,
	0x77, 0xa3, 0x6e, 0xe2, 0x67, 0x68, 0xf1, 0xd4, 0xf6, 0x25, 0xea, 0xb4, 0xa2, 0x76, 0xeb, 0x13,
	0x17, 0xd8, 0xf6, 0x36, 0xea, 0xbc, 0xa4, 0x8c, 0x8a, 0x58, 0x0c, 0x65, 0x11, 0xc2, 0x3a, 0x6a,
	0x67, 0x2a, 0x2f, 0x15, 0x90, 0xd9, 0xbf, 0xef, 0x5c, 0x3d, 0x52, 0x47, 0xa7, 0x3b, 0x98, 0x2a,
	0x52, 0xf0, 0x4a, 0xae, 0xfd, 0xc3, 0x40, 0xe6, 0x50, 0x1f, 0xdc, 0x02, 0x48, 0xf0, 0x3c, 0x9a,
	0x0e, 0x28, 0x83, 0xb4, 0x4c, 0x5d, 0x03, 0xfc, 0x1a, 0x75, 0x24, 0x48, 0x92, 0x8c, 0x0a, 0x4d,
	0x1a, 0xa8, 0xa8, 0x3b, 0x83, 0xb5, 0x42, 0xe9, 0xeb, 0x51, 0xef, 0xae, 0x1e, 0xad, 0x08, 0xf6,
	0x9c, 0x18, 0xdc, 0x94, 0xc8, 0xc8, 0xd9, 0xa4, 0x21, 0x19, 0x4f, 0xd6, 0xe9, 0xf8, 0xe7, 0x51,
	0xef, 0xd6, 0x84, 0xa4, 0xc9, 0x9a, 0x7d, 0x56, 0xc0, 0xf6, 0x4c, 0x05, 0x87, 0x0a, 0x9d, 0x91,
	0x8f, 0x08, 0xa7, 0x45, 0xee, 0xd7, 0x96, 0x57, 0x02, 0xb5, 0xbc, 0x46, 0xef, 0x0c, 0x34, 0xbb,
	0x23, 0x28, 0x57, 0xb7, 0xe1, 0x2e, 0x9a, 0x21, 0x41, 0xc0, 0xa9, 0x10, 0xe5, 0x3b, 0x56, 0x10,
	0x6f, 0xa2, 0x76, 0x69, 0x40, 0xbf, 0xdf, 0xa3, 0x3f, 0x33, 0x30, 0xa7, 0x0d, 0x54, 0x57, 0x97,
	0x1a, 0x45, 0x92, 0x6a, 0xc6, 0xea, 0x6d, 0x5a, 0x9e, 0x06, 0xf6, 0x67, 0x03, 0xcd, 0xed, 0x54,
	0x23, 0xde, 0x60, 0xbb, 0x70, 0xb5, 0x1f, 0x92, 0x42, 0xce, 0xe4, 0xb5, 0xfc, 0x68, 0xaa, 0xed,
	0x95, 0x1a, 0xa7, 0x93, 0x6d, 0x9d, 0x9d, 0xec, 0x3d, 0xd4, 0xd1, 0x1b, 0xa7, 0x17, 0x52, 0x2d,
	0x70, 0xcb, 0x33, 0x75, 0x4d, 0xad, 0xa0, 0xfd, 0xa1, 0x89, 0xe6, 0xd4, 0xd3, 0x90, 0x91, 0x4c,
	0x44, 0x20, 0x2f, 0xad, 0x83, 0xf1, 0x6f, 0xd7, 0xa1, 0xf9, 0x57, 0xd7, 0x01, 0x3f, 0x47, 0x33,
	0xea, 0x5a, 0xae, 0x3f, 0x70, 0xb3, 0xbf, 0xf2, 0xbb, 0x2f, 0xa7, 0x5e, 0x1e, 0xaf, 0x62, 0x0e,
	0x86, 0x07, 0xc7, 0x96, 0x71, 0x78, 0x6c, 0x19, 0xdf, 0x8f, 0x2d, 0xe3, 0xfd, 0x89, 0xd5, 0x38,
	0x3c, 0xb1, 0x1a, 0x5f, 0x4e, 0xac, 0xc6, 0xab, 0xa7, 0x61, 0x2c, 0xa3, 0xdc, 0x77, 0xc6, 0x90,
	0xba, 0xca, 0x69, 0x2c, 0x1e, 0x24, 0xc4, 0x17, 0x15, 0x70, 0xf7, 0xfb, 0x4f, 0xdc, 0xb7, 0x17,
	0x7e, 0xd5, 0x72, 0x92, 0x51, 0xe1, 0xb7, 0xd5, 0x3f, 0xeb, 0xe1, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xb6, 0x1c, 0x81, 0x53, 0xd1, 0x05, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UnbondingEpochIdentifier) > 0 {
		i -= len(m.UnbondingEpochIdentifier)
		copy(dAtA[i:], m.UnbondingEpochIdentifier)
		i = encodeVarintStablestaking(dAtA, i, uint64(len(m.UnbondingEpochIdentifier)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.RewardEpochIdentifier) > 0 {
		i -= len(m.RewardEpochIdentifier)
		copy(dAtA[i:], m.RewardEpochIdentifier)
		i = encodeVarintStablestaking(dAtA, i, uint64(len(m.RewardEpochIdentifier)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SupportedTokens) > 0 {
		for iNdEx := len(m.SupportedTokens) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SupportedTokens[iNdEx])
			copy(dAtA[i:], m.SupportedTokens[iNdEx])
			i = encodeVarintStablestaking(dAtA, i, uint64(len(m.SupportedTokens[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.UnbondingDuration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.UnbondingDuration):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintStablestaking(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	if len(m.RewardRate) > 0 {
		i -= len(m.RewardRate)
		copy(dAtA[i:], m.RewardRate)
		i = encodeVarintStablestaking(dAtA, i, uint64(len(m.RewardRate)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintStablestaking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *StakingPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StakingPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StakingPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalShares.Size()
		i -= size
		if _, err := m.TotalShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintStablestaking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.TotalStaked.Size()
		i -= size
		if _, err := m.TotalStaked.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintStablestaking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintStablestaking(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UserStake) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserStake) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserStake) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Epoch != 0 {
		i = encodeVarintStablestaking(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.Shares.Size()
		i -= size
		if _, err := m.Shares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintStablestaking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintStablestaking(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UnbondingInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnbondingInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UnbondingInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UnbondEpoch != 0 {
		i = encodeVarintStablestaking(dAtA, i, uint64(m.UnbondEpoch))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintStablestaking(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintStablestaking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintStablestaking(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EpochSnapshot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochSnapshot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochSnapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Stakers) > 0 {
		for iNdEx := len(m.Stakers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Stakers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStablestaking(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size := m.TotalShares.Size()
		i -= size
		if _, err := m.TotalShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintStablestaking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.TotalStaked.Size()
		i -= size
		if _, err := m.TotalStaked.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintStablestaking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintStablestaking(dAtA []byte, offset int, v uint64) int {
	offset -= sovStablestaking(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RewardRate)
	if l > 0 {
		n += 1 + l + sovStablestaking(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.UnbondingDuration)
	n += 1 + l + sovStablestaking(uint64(l))
	if len(m.SupportedTokens) > 0 {
		for _, s := range m.SupportedTokens {
			l = len(s)
			n += 1 + l + sovStablestaking(uint64(l))
		}
	}
	l = len(m.RewardEpochIdentifier)
	if l > 0 {
		n += 1 + l + sovStablestaking(uint64(l))
	}
	l = len(m.UnbondingEpochIdentifier)
	if l > 0 {
		n += 1 + l + sovStablestaking(uint64(l))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovStablestaking(uint64(l))
	return n
}

func (m *StakingPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovStablestaking(uint64(l))
	}
	l = m.TotalStaked.Size()
	n += 1 + l + sovStablestaking(uint64(l))
	l = m.TotalShares.Size()
	n += 1 + l + sovStablestaking(uint64(l))
	return n
}

func (m *UserStake) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovStablestaking(uint64(l))
	}
	l = m.Shares.Size()
	n += 1 + l + sovStablestaking(uint64(l))
	if m.Epoch != 0 {
		n += 1 + sovStablestaking(uint64(m.Epoch))
	}
	return n
}

func (m *UnbondingInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovStablestaking(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovStablestaking(uint64(l))
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovStablestaking(uint64(l))
	}
	if m.UnbondEpoch != 0 {
		n += 1 + sovStablestaking(uint64(m.UnbondEpoch))
	}
	return n
}

func (m *EpochSnapshot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TotalStaked.Size()
	n += 1 + l + sovStablestaking(uint64(l))
	l = m.TotalShares.Size()
	n += 1 + l + sovStablestaking(uint64(l))
	if len(m.Stakers) > 0 {
		for _, e := range m.Stakers {
			l = e.Size()
			n += 1 + l + sovStablestaking(uint64(l))
		}
	}
	return n
}

func sovStablestaking(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStablestaking(x uint64) (n int) {
	return sovStablestaking(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStablestaking
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStablestaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStablestaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStablestaking
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStablestaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.UnbondingDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupportedTokens", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStablestaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStablestaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SupportedTokens = append(m.SupportedTokens, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardEpochIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStablestaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStablestaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardEpochIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingEpochIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStablestaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStablestaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnbondingEpochIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStablestaking(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStablestaking
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStablestaking
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStablestaking
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStablestaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStablestaking(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStablestaking
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StakingPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStablestaking
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StakingPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StakingPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStablestaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStablestaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalStaked", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStablestaking
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStablestaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalStaked.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalShares", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStablestaking
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStablestaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStablestaking(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStablestaking
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserStake) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStablestaking
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserStake: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserStake: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStablestaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStablestaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shares", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStablestaking
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStablestaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Shares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStablestaking(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStablestaking
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UnbondingInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStablestaking
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnbondingInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnbondingInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStablestaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStablestaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStablestaking
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStablestaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStablestaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStablestaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondEpoch", wireType)
			}
			m.UnbondEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondEpoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStablestaking(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStablestaking
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochSnapshot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStablestaking
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochSnapshot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochSnapshot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalStaked", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStablestaking
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStablestaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalStaked.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalShares", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStablestaking
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStablestaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stakers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStablestaking
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStablestaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Stakers = append(m.Stakers, &UserStake{})
			if err := m.Stakers[len(m.Stakers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStablestaking(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStablestaking
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStablestaking(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStablestaking
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStablestaking
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStablestaking
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStablestaking
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStablestaking
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStablestaking        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStablestaking          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStablestaking = fmt.Errorf("proto: unexpected end of group")
)
