// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: symphony/stablestaking/v1beta1/tx.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgStakeTokens struct {
	Staker string     `protobuf:"bytes,1,opt,name=staker,proto3" json:"staker,omitempty" yaml:"staker"`
	Amount types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount" yaml:"amount"`
}

func (m *MsgStakeTokens) Reset()         { *m = MsgStakeTokens{} }
func (m *MsgStakeTokens) String() string { return proto.CompactTextString(m) }
func (*MsgStakeTokens) ProtoMessage()    {}
func (*MsgStakeTokens) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9cf5e1ac5985f34, []int{0}
}
func (m *MsgStakeTokens) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStakeTokens) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStakeTokens.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStakeTokens) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStakeTokens.Merge(m, src)
}
func (m *MsgStakeTokens) XXX_Size() int {
	return m.Size()
}
func (m *MsgStakeTokens) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStakeTokens.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStakeTokens proto.InternalMessageInfo

type MsgStakeTokensResponse struct {
	Staker      string                      `protobuf:"bytes,1,opt,name=staker,proto3" json:"staker,omitempty" yaml:"staker"`
	Amount      *types.Coin                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	TotalStaked cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=total_staked,json=totalStaked,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"total_staked" yaml:"total_staked"`
	TotalShares cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=total_shares,json=totalShares,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"total_shares" yaml:"total_shares"`
}

func (m *MsgStakeTokensResponse) Reset()         { *m = MsgStakeTokensResponse{} }
func (m *MsgStakeTokensResponse) String() string { return proto.CompactTextString(m) }
func (*MsgStakeTokensResponse) ProtoMessage()    {}
func (*MsgStakeTokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9cf5e1ac5985f34, []int{1}
}
func (m *MsgStakeTokensResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStakeTokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStakeTokensResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStakeTokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStakeTokensResponse.Merge(m, src)
}
func (m *MsgStakeTokensResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgStakeTokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStakeTokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStakeTokensResponse proto.InternalMessageInfo

func (m *MsgStakeTokensResponse) GetStaker() string {
	if m != nil {
		return m.Staker
	}
	return ""
}

func (m *MsgStakeTokensResponse) GetAmount() *types.Coin {
	if m != nil {
		return m.Amount
	}
	return nil
}

type MsgUnstakeTokens struct {
	Staker string     `protobuf:"bytes,1,opt,name=staker,proto3" json:"staker,omitempty" yaml:"staker"`
	Amount types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount" yaml:"amount"`
}

func (m *MsgUnstakeTokens) Reset()         { *m = MsgUnstakeTokens{} }
func (m *MsgUnstakeTokens) String() string { return proto.CompactTextString(m) }
func (*MsgUnstakeTokens) ProtoMessage()    {}
func (*MsgUnstakeTokens) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9cf5e1ac5985f34, []int{2}
}
func (m *MsgUnstakeTokens) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnstakeTokens) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnstakeTokens.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnstakeTokens) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnstakeTokens.Merge(m, src)
}
func (m *MsgUnstakeTokens) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnstakeTokens) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnstakeTokens.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnstakeTokens proto.InternalMessageInfo

type MsgUnstakeTokensResponse struct {
	Staker      string                      `protobuf:"bytes,1,opt,name=staker,proto3" json:"staker,omitempty" yaml:"staker"`
	Amount      types.DecCoin               `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount" yaml:"amount"`
	TotalStaked cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=total_staked,json=totalStaked,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"total_staked" yaml:"total_staked"`
	TotalShares cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=total_shares,json=totalShares,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"total_shares" yaml:"total_shares"`
}

func (m *MsgUnstakeTokensResponse) Reset()         { *m = MsgUnstakeTokensResponse{} }
func (m *MsgUnstakeTokensResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUnstakeTokensResponse) ProtoMessage()    {}
func (*MsgUnstakeTokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9cf5e1ac5985f34, []int{3}
}
func (m *MsgUnstakeTokensResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnstakeTokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnstakeTokensResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnstakeTokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnstakeTokensResponse.Merge(m, src)
}
func (m *MsgUnstakeTokensResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnstakeTokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnstakeTokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnstakeTokensResponse proto.InternalMessageInfo

func (m *MsgUnstakeTokensResponse) GetStaker() string {
	if m != nil {
		return m.Staker
	}
	return ""
}

func (m *MsgUnstakeTokensResponse) GetAmount() types.DecCoin {
	if m != nil {
		return m.Amount
	}
	return types.DecCoin{}
}

type MsgClaimRewardByToken struct {
	Staker string `protobuf:"bytes,1,opt,name=staker,proto3" json:"staker,omitempty" yaml:"staker"`
	Token  string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (m *MsgClaimRewardByToken) Reset()         { *m = MsgClaimRewardByToken{} }
func (m *MsgClaimRewardByToken) String() string { return proto.CompactTextString(m) }
func (*MsgClaimRewardByToken) ProtoMessage()    {}
func (*MsgClaimRewardByToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9cf5e1ac5985f34, []int{4}
}
func (m *MsgClaimRewardByToken) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimRewardByToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimRewardByToken.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimRewardByToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimRewardByToken.Merge(m, src)
}
func (m *MsgClaimRewardByToken) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimRewardByToken) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimRewardByToken.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimRewardByToken proto.InternalMessageInfo

type MsgClaimRewardByTokenResponse struct {
	Reward *types.Coin `protobuf:"bytes,1,opt,name=reward,proto3" json:"reward,omitempty"`
}

func (m *MsgClaimRewardByTokenResponse) Reset()         { *m = MsgClaimRewardByTokenResponse{} }
func (m *MsgClaimRewardByTokenResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimRewardByTokenResponse) ProtoMessage()    {}
func (*MsgClaimRewardByTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9cf5e1ac5985f34, []int{5}
}
func (m *MsgClaimRewardByTokenResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimRewardByTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimRewardByTokenResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimRewardByTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimRewardByTokenResponse.Merge(m, src)
}
func (m *MsgClaimRewardByTokenResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimRewardByTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimRewardByTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimRewardByTokenResponse proto.InternalMessageInfo

func (m *MsgClaimRewardByTokenResponse) GetReward() *types.Coin {
	if m != nil {
		return m.Reward
	}
	return nil
}

type MsgClaimAllRewards struct {
	Staker string `protobuf:"bytes,1,opt,name=staker,proto3" json:"staker,omitempty" yaml:"staker"`
}

func (m *MsgClaimAllRewards) Reset()         { *m = MsgClaimAllRewards{} }
func (m *MsgClaimAllRewards) String() string { return proto.CompactTextString(m) }
func (*MsgClaimAllRewards) ProtoMessage()    {}
func (*MsgClaimAllRewards) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9cf5e1ac5985f34, []int{6}
}
func (m *MsgClaimAllRewards) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimAllRewards) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimAllRewards.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimAllRewards) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimAllRewards.Merge(m, src)
}
func (m *MsgClaimAllRewards) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimAllRewards) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimAllRewards.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimAllRewards proto.InternalMessageInfo

type MsgClaimAllRewardsResponse struct {
	Rewards []*types.Coin `protobuf:"bytes,1,rep,name=rewards,proto3" json:"rewards,omitempty"`
}

func (m *MsgClaimAllRewardsResponse) Reset()         { *m = MsgClaimAllRewardsResponse{} }
func (m *MsgClaimAllRewardsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimAllRewardsResponse) ProtoMessage()    {}
func (*MsgClaimAllRewardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9cf5e1ac5985f34, []int{7}
}
func (m *MsgClaimAllRewardsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimAllRewardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimAllRewardsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimAllRewardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimAllRewardsResponse.Merge(m, src)
}
func (m *MsgClaimAllRewardsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimAllRewardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimAllRewardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimAllRewardsResponse proto.InternalMessageInfo

func (m *MsgClaimAllRewardsResponse) GetRewards() []*types.Coin {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgStakeTokens)(nil), "symphony.stablestaking.v1beta1.MsgStakeTokens")
	proto.RegisterType((*MsgStakeTokensResponse)(nil), "symphony.stablestaking.v1beta1.MsgStakeTokensResponse")
	proto.RegisterType((*MsgUnstakeTokens)(nil), "symphony.stablestaking.v1beta1.MsgUnstakeTokens")
	proto.RegisterType((*MsgUnstakeTokensResponse)(nil), "symphony.stablestaking.v1beta1.MsgUnstakeTokensResponse")
	proto.RegisterType((*MsgClaimRewardByToken)(nil), "symphony.stablestaking.v1beta1.MsgClaimRewardByToken")
	proto.RegisterType((*MsgClaimRewardByTokenResponse)(nil), "symphony.stablestaking.v1beta1.MsgClaimRewardByTokenResponse")
	proto.RegisterType((*MsgClaimAllRewards)(nil), "symphony.stablestaking.v1beta1.MsgClaimAllRewards")
	proto.RegisterType((*MsgClaimAllRewardsResponse)(nil), "symphony.stablestaking.v1beta1.MsgClaimAllRewardsResponse")
}

func init() {
	proto.RegisterFile("symphony/stablestaking/v1beta1/tx.proto", fileDescriptor_b9cf5e1ac5985f34)
}

var fileDescriptor_b9cf5e1ac5985f34 = []byte{
	// 691 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x95, 0x4f, 0x4f, 0x13, 0x4f,
	0x18, 0xc7, 0x3b, 0xe5, 0xf7, 0xab, 0x61, 0x00, 0x63, 0x0a, 0x68, 0x59, 0x71, 0xdb, 0xec, 0x45,
	0x24, 0xb2, 0x63, 0x21, 0x11, 0xe9, 0x8d, 0xc2, 0xc1, 0x44, 0x7b, 0x70, 0xd1, 0x8b, 0x89, 0x21,
	0xb3, 0xed, 0xb8, 0xdd, 0x74, 0x77, 0xa6, 0xd9, 0x99, 0x22, 0x7b, 0x25, 0x31, 0xf1, 0x68, 0xe2,
	0x1b, 0xe0, 0x15, 0x18, 0x63, 0x88, 0xaf, 0x81, 0x83, 0x07, 0xa2, 0x17, 0xe3, 0xa1, 0x31, 0x60,
	0x22, 0x37, 0x13, 0x5e, 0x81, 0xd9, 0x99, 0xdd, 0xda, 0x42, 0xc3, 0x1f, 0xd3, 0x0b, 0xa7, 0xf6,
	0x99, 0x79, 0xbe, 0xdf, 0xf9, 0x3c, 0xcf, 0xcc, 0xce, 0xc0, 0xdb, 0x3c, 0xf4, 0x9b, 0x75, 0x46,
	0x43, 0xc4, 0x05, 0xb6, 0x3d, 0xc2, 0x05, 0x6e, 0xb8, 0xd4, 0x41, 0x1b, 0x45, 0x9b, 0x08, 0x5c,
	0x44, 0x62, 0xd3, 0x6c, 0x06, 0x4c, 0xb0, 0xac, 0x9e, 0x24, 0x9a, 0x3d, 0x89, 0x66, 0x9c, 0xa8,
	0xe9, 0x55, 0xc6, 0x7d, 0xc6, 0x91, 0x8d, 0x39, 0xe9, 0xa8, 0xab, 0xcc, 0xa5, 0x4a, 0xaf, 0x69,
	0xf1, 0xbc, 0xd8, 0x3c, 0xe1, 0xad, 0x4d, 0x39, 0x8c, 0x39, 0x1e, 0x41, 0x32, 0xb2, 0x5b, 0x2f,
	0x11, 0xa6, 0x61, 0x32, 0xa5, 0x64, 0xeb, 0x32, 0x42, 0x2a, 0x88, 0xa7, 0x26, 0x1c, 0xe6, 0x30,
	0x35, 0x1e, 0xfd, 0x8b, 0x47, 0xa7, 0x63, 0x2f, 0xdc, 0x74, 0x11, 0xa6, 0x94, 0x09, 0x2c, 0x5c,
	0x46, 0x13, 0xcd, 0x8d, 0x98, 0xc2, 0xe7, 0x51, 0x89, 0xd1, 0x8f, 0x9a, 0x30, 0x3e, 0x02, 0x78,
	0xb5, 0xc2, 0x9d, 0x35, 0x81, 0x1b, 0xe4, 0x29, 0x6b, 0x10, 0xca, 0xb3, 0xcb, 0x30, 0x13, 0x15,
	0x49, 0x82, 0x1c, 0x28, 0x80, 0x99, 0xe1, 0xf2, 0x9d, 0xa3, 0x76, 0x7e, 0x2c, 0xc4, 0xbe, 0x57,
	0x32, 0xd4, 0xb8, 0xf1, 0x65, 0x67, 0x6e, 0x22, 0x46, 0x5a, 0xae, 0xd5, 0x02, 0xc2, 0xf9, 0x9a,
	0x08, 0x5c, 0xea, 0x58, 0xb1, 0x30, 0xfb, 0x10, 0x66, 0xb0, 0xcf, 0x5a, 0x54, 0xe4, 0xd2, 0x05,
	0x30, 0x33, 0x32, 0x3f, 0x65, 0xc6, 0xe9, 0x51, 0x97, 0x92, 0xd6, 0x99, 0x2b, 0xcc, 0xa5, 0xe5,
	0xc9, 0xdd, 0x76, 0x3e, 0xf5, 0x77, 0x05, 0x25, 0x33, 0xac, 0x58, 0x5f, 0x1a, 0x7f, 0xb3, 0x9d,
	0x4f, 0x1d, 0x6e, 0xe7, 0x53, 0x5b, 0xbf, 0x3e, 0xcc, 0xc6, 0xf6, 0xc6, 0xe7, 0x34, 0xbc, 0xde,
	0x0b, 0x6d, 0x11, 0xde, 0x64, 0x94, 0x93, 0x41, 0xc0, 0x17, 0xcf, 0x0d, 0x9f, 0x50, 0x66, 0x5f,
	0xc0, 0x51, 0xc1, 0x04, 0xf6, 0xd6, 0xa5, 0x45, 0x2d, 0x37, 0x54, 0x00, 0x33, 0xa3, 0xe5, 0x52,
	0x54, 0xda, 0xf7, 0x76, 0xfe, 0xa6, 0xd2, 0xf3, 0x5a, 0xc3, 0x74, 0x19, 0xf2, 0xb1, 0xa8, 0x9b,
	0x8f, 0x89, 0x83, 0xab, 0xe1, 0x2a, 0xa9, 0x1e, 0xb5, 0xf3, 0xe3, 0x0a, 0xaf, 0xdb, 0xc0, 0xb0,
	0x46, 0x64, 0x28, 0x2b, 0xac, 0x75, 0xd9, 0xd7, 0x71, 0x40, 0x78, 0xee, 0xbf, 0x7f, 0xb7, 0x97,
	0x06, 0x1d, 0x7b, 0x15, 0xed, 0x00, 0x78, 0xad, 0xc2, 0x9d, 0x67, 0x94, 0x5f, 0xaa, 0x53, 0x70,
	0x98, 0x86, 0xb9, 0xe3, 0xd8, 0x83, 0x3c, 0x07, 0x8f, 0x8e, 0xe1, 0x4f, 0xf7, 0xc5, 0x5f, 0x25,
	0xd5, 0x73, 0x54, 0x70, 0xc9, 0x4f, 0xc8, 0x6b, 0x00, 0x27, 0x2b, 0xdc, 0x59, 0xf1, 0xb0, 0xeb,
	0x5b, 0xe4, 0x15, 0x0e, 0x6a, 0xe5, 0x50, 0x36, 0x7c, 0x10, 0x7d, 0x9e, 0x80, 0xff, 0x8b, 0xc8,
	0x4b, 0xb6, 0x79, 0xd8, 0x52, 0x41, 0xff, 0x2d, 0xb7, 0xe0, 0xad, 0xbe, 0x18, 0x9d, 0x6d, 0x2f,
	0xc2, 0x4c, 0x20, 0x27, 0x24, 0xce, 0xe9, 0xdf, 0xae, 0x4a, 0x34, 0x3c, 0x98, 0x4d, 0x3c, 0x97,
	0x3d, 0x4f, 0xd9, 0x0e, 0xe2, 0xf8, 0xf7, 0xaf, 0xe0, 0x09, 0xd4, 0x4e, 0xae, 0xd6, 0xc1, 0x5f,
	0x80, 0x57, 0x14, 0x15, 0xcf, 0x81, 0xc2, 0xd0, 0xe9, 0xfc, 0x49, 0xe6, 0xfc, 0xef, 0x34, 0x1c,
	0xaa, 0x70, 0x27, 0xfb, 0x1e, 0xc0, 0x91, 0xee, 0x7b, 0xdc, 0x34, 0x4f, 0x7f, 0xba, 0xcc, 0xde,
	0x2b, 0x54, 0xbb, 0x7f, 0xb1, 0xfc, 0x04, 0xda, 0x58, 0xdc, 0xfa, 0xfa, 0xf3, 0x5d, 0xba, 0x58,
	0x02, 0xb3, 0xc6, 0x5d, 0x74, 0xc6, 0xb3, 0x2a, 0xbb, 0xb0, 0x2e, 0x14, 0xe0, 0x27, 0x00, 0xc7,
	0x7a, 0x2f, 0x9d, 0x7b, 0xe7, 0x40, 0xe8, 0x51, 0x68, 0x0f, 0x2e, 0xaa, 0xe8, 0x60, 0x2f, 0x49,
	0xec, 0x85, 0x08, 0xdb, 0x3c, 0x0b, 0xbb, 0x45, 0xbb, 0xc1, 0xcb, 0x6b, 0xbb, 0xfb, 0x3a, 0xd8,
	0xdb, 0xd7, 0xc1, 0x8f, 0x7d, 0x1d, 0xbc, 0x3d, 0xd0, 0x53, 0x7b, 0x07, 0x7a, 0xea, 0xdb, 0x81,
	0x9e, 0x7a, 0xbe, 0xe4, 0xb8, 0xa2, 0xde, 0xb2, 0xcd, 0x2a, 0xf3, 0x91, 0xdc, 0x38, 0x97, 0xcf,
	0x79, 0xd8, 0xe6, 0x49, 0x80, 0x36, 0xe6, 0x17, 0xd1, 0xe6, 0xb1, 0x55, 0x44, 0xd8, 0x24, 0xdc,
	0xce, 0xc8, 0x07, 0x79, 0xe1, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xac, 0x4a, 0x8f, 0x9a,
	0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	StakeTokens(ctx context.Context, in *MsgStakeTokens, opts ...grpc.CallOption) (*MsgStakeTokensResponse, error)
	UnstakeTokens(ctx context.Context, in *MsgUnstakeTokens, opts ...grpc.CallOption) (*MsgUnstakeTokensResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) StakeTokens(ctx context.Context, in *MsgStakeTokens, opts ...grpc.CallOption) (*MsgStakeTokensResponse, error) {
	out := new(MsgStakeTokensResponse)
	err := c.cc.Invoke(ctx, "/symphony.stablestaking.v1beta1.Msg/StakeTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnstakeTokens(ctx context.Context, in *MsgUnstakeTokens, opts ...grpc.CallOption) (*MsgUnstakeTokensResponse, error) {
	out := new(MsgUnstakeTokensResponse)
	err := c.cc.Invoke(ctx, "/symphony.stablestaking.v1beta1.Msg/UnstakeTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	StakeTokens(context.Context, *MsgStakeTokens) (*MsgStakeTokensResponse, error)
	UnstakeTokens(context.Context, *MsgUnstakeTokens) (*MsgUnstakeTokensResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) StakeTokens(ctx context.Context, req *MsgStakeTokens) (*MsgStakeTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StakeTokens not implemented")
}
func (*UnimplementedMsgServer) UnstakeTokens(ctx context.Context, req *MsgUnstakeTokens) (*MsgUnstakeTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnstakeTokens not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_StakeTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgStakeTokens)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).StakeTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/symphony.stablestaking.v1beta1.Msg/StakeTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).StakeTokens(ctx, req.(*MsgStakeTokens))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnstakeTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnstakeTokens)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnstakeTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/symphony.stablestaking.v1beta1.Msg/UnstakeTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnstakeTokens(ctx, req.(*MsgUnstakeTokens))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "symphony.stablestaking.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StakeTokens",
			Handler:    _Msg_StakeTokens_Handler,
		},
		{
			MethodName: "UnstakeTokens",
			Handler:    _Msg_UnstakeTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "symphony/stablestaking/v1beta1/tx.proto",
}

func (m *MsgStakeTokens) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStakeTokens) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStakeTokens) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Staker) > 0 {
		i -= len(m.Staker)
		copy(dAtA[i:], m.Staker)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Staker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgStakeTokensResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStakeTokensResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStakeTokensResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalShares.Size()
		i -= size
		if _, err := m.TotalShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.TotalStaked.Size()
		i -= size
		if _, err := m.TotalStaked.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Amount != nil {
		{
			size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Staker) > 0 {
		i -= len(m.Staker)
		copy(dAtA[i:], m.Staker)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Staker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUnstakeTokens) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnstakeTokens) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnstakeTokens) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Staker) > 0 {
		i -= len(m.Staker)
		copy(dAtA[i:], m.Staker)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Staker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUnstakeTokensResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnstakeTokensResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnstakeTokensResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalShares.Size()
		i -= size
		if _, err := m.TotalShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.TotalStaked.Size()
		i -= size
		if _, err := m.TotalStaked.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Staker) > 0 {
		i -= len(m.Staker)
		copy(dAtA[i:], m.Staker)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Staker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimRewardByToken) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimRewardByToken) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimRewardByToken) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Staker) > 0 {
		i -= len(m.Staker)
		copy(dAtA[i:], m.Staker)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Staker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimRewardByTokenResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimRewardByTokenResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimRewardByTokenResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reward != nil {
		{
			size, err := m.Reward.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimAllRewards) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimAllRewards) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimAllRewards) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Staker) > 0 {
		i -= len(m.Staker)
		copy(dAtA[i:], m.Staker)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Staker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimAllRewardsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimAllRewardsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimAllRewardsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Rewards) > 0 {
		for iNdEx := len(m.Rewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Rewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgStakeTokens) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Staker)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgStakeTokensResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Staker)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != nil {
		l = m.Amount.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.TotalStaked.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.TotalShares.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUnstakeTokens) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Staker)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUnstakeTokensResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Staker)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.TotalStaked.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.TotalShares.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgClaimRewardByToken) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Staker)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClaimRewardByTokenResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Reward != nil {
		l = m.Reward.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClaimAllRewards) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Staker)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClaimAllRewardsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Rewards) > 0 {
		for _, e := range m.Rewards {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgStakeTokens) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStakeTokens: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStakeTokens: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Staker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Staker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStakeTokensResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStakeTokensResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStakeTokensResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Staker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Staker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Amount == nil {
				m.Amount = &types.Coin{}
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalStaked", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalStaked.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalShares", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnstakeTokens) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnstakeTokens: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnstakeTokens: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Staker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Staker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnstakeTokensResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnstakeTokensResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnstakeTokensResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Staker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Staker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalStaked", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalStaked.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalShares", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimRewardByToken) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimRewardByToken: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimRewardByToken: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Staker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Staker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimRewardByTokenResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimRewardByTokenResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimRewardByTokenResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reward", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Reward == nil {
				m.Reward = &types.Coin{}
			}
			if err := m.Reward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimAllRewards) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimAllRewards: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimAllRewards: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Staker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Staker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimAllRewardsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimAllRewardsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimAllRewardsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rewards = append(m.Rewards, &types.Coin{})
			if err := m.Rewards[len(m.Rewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
