// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: symphony/stablestaking/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgStakeTokens struct {
	Staker string      `protobuf:"bytes,1,opt,name=staker,proto3" json:"staker,omitempty"`
	Amount *types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgStakeTokens) Reset()         { *m = MsgStakeTokens{} }
func (m *MsgStakeTokens) String() string { return proto.CompactTextString(m) }
func (*MsgStakeTokens) ProtoMessage()    {}
func (*MsgStakeTokens) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9cf5e1ac5985f34, []int{0}
}
func (m *MsgStakeTokens) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStakeTokens) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStakeTokens.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStakeTokens) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStakeTokens.Merge(m, src)
}
func (m *MsgStakeTokens) XXX_Size() int {
	return m.Size()
}
func (m *MsgStakeTokens) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStakeTokens.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStakeTokens proto.InternalMessageInfo

func (m *MsgStakeTokens) GetStaker() string {
	if m != nil {
		return m.Staker
	}
	return ""
}

func (m *MsgStakeTokens) GetAmount() *types.Coin {
	if m != nil {
		return m.Amount
	}
	return nil
}

type MsgStakeTokensResponse struct {
}

func (m *MsgStakeTokensResponse) Reset()         { *m = MsgStakeTokensResponse{} }
func (m *MsgStakeTokensResponse) String() string { return proto.CompactTextString(m) }
func (*MsgStakeTokensResponse) ProtoMessage()    {}
func (*MsgStakeTokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9cf5e1ac5985f34, []int{1}
}
func (m *MsgStakeTokensResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStakeTokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStakeTokensResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStakeTokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStakeTokensResponse.Merge(m, src)
}
func (m *MsgStakeTokensResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgStakeTokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStakeTokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStakeTokensResponse proto.InternalMessageInfo

type MsgUnstakeTokens struct {
	Staker string      `protobuf:"bytes,1,opt,name=staker,proto3" json:"staker,omitempty"`
	Amount *types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgUnstakeTokens) Reset()         { *m = MsgUnstakeTokens{} }
func (m *MsgUnstakeTokens) String() string { return proto.CompactTextString(m) }
func (*MsgUnstakeTokens) ProtoMessage()    {}
func (*MsgUnstakeTokens) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9cf5e1ac5985f34, []int{2}
}
func (m *MsgUnstakeTokens) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnstakeTokens) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnstakeTokens.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnstakeTokens) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnstakeTokens.Merge(m, src)
}
func (m *MsgUnstakeTokens) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnstakeTokens) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnstakeTokens.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnstakeTokens proto.InternalMessageInfo

func (m *MsgUnstakeTokens) GetStaker() string {
	if m != nil {
		return m.Staker
	}
	return ""
}

func (m *MsgUnstakeTokens) GetAmount() *types.Coin {
	if m != nil {
		return m.Amount
	}
	return nil
}

type MsgUnstakeTokensResponse struct {
}

func (m *MsgUnstakeTokensResponse) Reset()         { *m = MsgUnstakeTokensResponse{} }
func (m *MsgUnstakeTokensResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUnstakeTokensResponse) ProtoMessage()    {}
func (*MsgUnstakeTokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9cf5e1ac5985f34, []int{3}
}
func (m *MsgUnstakeTokensResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnstakeTokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnstakeTokensResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnstakeTokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnstakeTokensResponse.Merge(m, src)
}
func (m *MsgUnstakeTokensResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnstakeTokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnstakeTokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnstakeTokensResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgStakeTokens)(nil), "symphony.stablestaking.v1beta1.MsgStakeTokens")
	proto.RegisterType((*MsgStakeTokensResponse)(nil), "symphony.stablestaking.v1beta1.MsgStakeTokensResponse")
	proto.RegisterType((*MsgUnstakeTokens)(nil), "symphony.stablestaking.v1beta1.MsgUnstakeTokens")
	proto.RegisterType((*MsgUnstakeTokensResponse)(nil), "symphony.stablestaking.v1beta1.MsgUnstakeTokensResponse")
}

func init() {
	proto.RegisterFile("symphony/stablestaking/v1beta1/tx.proto", fileDescriptor_b9cf5e1ac5985f34)
}

var fileDescriptor_b9cf5e1ac5985f34 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xbf, 0x6e, 0x22, 0x31,
	0x10, 0xc6, 0xf1, 0x9d, 0x84, 0x74, 0x46, 0x77, 0x3a, 0x6d, 0x81, 0x16, 0x17, 0x16, 0xa2, 0x09,
	0x4d, 0xec, 0x40, 0xa4, 0xfc, 0x69, 0x93, 0x9a, 0x06, 0x92, 0x26, 0x51, 0x0a, 0x1b, 0x39, 0x66,
	0x05, 0xeb, 0x59, 0x31, 0x5e, 0xc4, 0x2a, 0x2f, 0x91, 0xc7, 0x4a, 0x49, 0x99, 0x32, 0x82, 0xa7,
	0x48, 0x17, 0x01, 0xbb, 0x51, 0x96, 0x48, 0x51, 0x28, 0x52, 0x8e, 0xe6, 0xfb, 0xbe, 0xdf, 0x8c,
	0x3d, 0xf4, 0x00, 0xb3, 0x38, 0x19, 0x81, 0xcb, 0x24, 0x7a, 0xa5, 0x27, 0x06, 0xbd, 0x1a, 0x47,
	0xce, 0xca, 0x59, 0x47, 0x1b, 0xaf, 0x3a, 0xd2, 0xcf, 0x45, 0x32, 0x05, 0x0f, 0x01, 0x2f, 0x84,
	0xa2, 0x24, 0x14, 0xb9, 0x90, 0xf1, 0x21, 0x60, 0x0c, 0x28, 0xb5, 0x42, 0xf3, 0xee, 0x1e, 0x42,
	0xe4, 0xb6, 0x7e, 0xc6, 0xf2, 0xbe, 0x9f, 0x7f, 0xca, 0x66, 0x0d, 0x0b, 0x60, 0x27, 0x46, 0x6e,
	0x2a, 0x9d, 0xde, 0x4b, 0xe5, 0xb2, 0x6d, 0xab, 0x75, 0x4b, 0xff, 0xf5, 0xd0, 0x0e, 0xbc, 0x1a,
	0x9b, 0x2b, 0x18, 0x1b, 0x87, 0x41, 0x9d, 0x56, 0xd7, 0x6c, 0x33, 0x0d, 0x49, 0x93, 0xb4, 0xff,
	0xf4, 0xf3, 0x2a, 0xe8, 0xd0, 0xaa, 0x8a, 0x21, 0x75, 0x3e, 0xfc, 0xd5, 0x24, 0xed, 0x5a, 0xb7,
	0x21, 0xb6, 0x44, 0xb1, 0x9e, 0xa8, 0x18, 0x53, 0x5c, 0x42, 0xe4, 0xfa, 0xb9, 0xb0, 0x15, 0xd2,
	0x7a, 0x39, 0xbc, 0x6f, 0x30, 0x01, 0x87, 0xa6, 0x75, 0x47, 0xff, 0xf7, 0xd0, 0x5e, 0x3b, 0xfc,
	0x19, 0x30, 0xa3, 0xe1, 0x6e, 0x7c, 0x81, 0xee, 0xbe, 0x12, 0xfa, 0xbb, 0x87, 0x36, 0x48, 0x69,
	0xed, 0xe3, 0xda, 0x42, 0x7c, 0xfd, 0x01, 0xa2, 0xbc, 0x09, 0x3b, 0xd9, 0x4f, 0x5f, 0xe0, 0x83,
	0x07, 0xfa, 0xb7, 0xbc, 0xf6, 0xd1, 0x37, 0x82, 0x4a, 0x0e, 0x76, 0xb6, 0xaf, 0xa3, 0x80, 0x5f,
	0x0c, 0x9e, 0x96, 0x9c, 0x2c, 0x96, 0x9c, 0xbc, 0x2c, 0x39, 0x79, 0x5c, 0xf1, 0xca, 0x62, 0xc5,
	0x2b, 0xcf, 0x2b, 0x5e, 0xb9, 0x39, 0xb7, 0x91, 0x1f, 0xa5, 0x5a, 0x0c, 0x21, 0x96, 0x9b, 0xd7,
	0x8d, 0xf0, 0x70, 0xa2, 0x34, 0x16, 0x85, 0x9c, 0x75, 0x4f, 0xe5, 0x7c, 0xe7, 0x88, 0x7d, 0x96,
	0x18, 0xd4, 0xd5, 0xcd, 0x25, 0x1d, 0xbf, 0x05, 0x00, 0x00, 0xff, 0xff, 0x23, 0xef, 0x07, 0xfd,
	0xeb, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	StakeTokens(ctx context.Context, in *MsgStakeTokens, opts ...grpc.CallOption) (*MsgStakeTokensResponse, error)
	UnstakeTokens(ctx context.Context, in *MsgUnstakeTokens, opts ...grpc.CallOption) (*MsgUnstakeTokensResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) StakeTokens(ctx context.Context, in *MsgStakeTokens, opts ...grpc.CallOption) (*MsgStakeTokensResponse, error) {
	out := new(MsgStakeTokensResponse)
	err := c.cc.Invoke(ctx, "/symphony.stablestaking.v1beta1.Msg/StakeTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnstakeTokens(ctx context.Context, in *MsgUnstakeTokens, opts ...grpc.CallOption) (*MsgUnstakeTokensResponse, error) {
	out := new(MsgUnstakeTokensResponse)
	err := c.cc.Invoke(ctx, "/symphony.stablestaking.v1beta1.Msg/UnstakeTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	StakeTokens(context.Context, *MsgStakeTokens) (*MsgStakeTokensResponse, error)
	UnstakeTokens(context.Context, *MsgUnstakeTokens) (*MsgUnstakeTokensResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) StakeTokens(ctx context.Context, req *MsgStakeTokens) (*MsgStakeTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StakeTokens not implemented")
}
func (*UnimplementedMsgServer) UnstakeTokens(ctx context.Context, req *MsgUnstakeTokens) (*MsgUnstakeTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnstakeTokens not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_StakeTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgStakeTokens)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).StakeTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/symphony.stablestaking.v1beta1.Msg/StakeTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).StakeTokens(ctx, req.(*MsgStakeTokens))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnstakeTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnstakeTokens)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnstakeTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/symphony.stablestaking.v1beta1.Msg/UnstakeTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnstakeTokens(ctx, req.(*MsgUnstakeTokens))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "symphony.stablestaking.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StakeTokens",
			Handler:    _Msg_StakeTokens_Handler,
		},
		{
			MethodName: "UnstakeTokens",
			Handler:    _Msg_UnstakeTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "symphony/stablestaking/v1beta1/tx.proto",
}

func (m *MsgStakeTokens) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStakeTokens) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStakeTokens) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != nil {
		{
			size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Staker) > 0 {
		i -= len(m.Staker)
		copy(dAtA[i:], m.Staker)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Staker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgStakeTokensResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStakeTokensResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStakeTokensResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUnstakeTokens) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnstakeTokens) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnstakeTokens) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != nil {
		{
			size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Staker) > 0 {
		i -= len(m.Staker)
		copy(dAtA[i:], m.Staker)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Staker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUnstakeTokensResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnstakeTokensResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnstakeTokensResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgStakeTokens) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Staker)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != nil {
		l = m.Amount.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgStakeTokensResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUnstakeTokens) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Staker)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != nil {
		l = m.Amount.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUnstakeTokensResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgStakeTokens) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStakeTokens: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStakeTokens: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Staker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Staker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Amount == nil {
				m.Amount = &types.Coin{}
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStakeTokensResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStakeTokensResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStakeTokensResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnstakeTokens) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnstakeTokens: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnstakeTokens: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Staker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Staker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Amount == nil {
				m.Amount = &types.Coin{}
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnstakeTokensResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnstakeTokensResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnstakeTokensResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
